In [6]:
from pathlib import Path
import sys
import pandas as pd
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt

#setup project root and paths
project_root = Path("/dcs/23/u2200504/thesis/recidivism-causal").resolve()

#set causal pitfalls root
cp_root = project_root / "data" / "raw" / "CausalPitfallsData"

#path to put results
output_dir = project_root/"results"/"graphs_DAGSLAM_scored"
output_dir.mkdir(parents=True,exist_ok=True)

#test it works
print("CP roots:" , cp_root)
print("Output directory:", output_dir)

CP roots: /dcs/23/u2200504/thesis/recidivism-causal/data/raw/CausalPitfallsData
Output directory: /dcs/23/u2200504/thesis/recidivism-causal/results/graphs_DAGSLAM_scored

In [3]:
#add dagslam implementation to system path
dagslam_path = project_root/"code"/"dagslam"/"DAGSLAM Causal Bayesian Network Structure Learning of Mixed Type Data"/"_dagslam"
sys.path.append(str(dagslam_path))

#uses DAGSLAM implementation code authored by Yuanyuan Zhao. 
#https://github.com/yuanyuan-zhao-pku/DAGSLAM/blob/main/DAGSLAM%20Causal%20Bayesian%20Network%20Structure%20Learning%20of%20Mixed%20Type%20Data/_dagslam/DAGSLAM.py
#DAGSLAM is an extension of the NOTEARS algorithm developed by Xun Zheng, et al.
import importlib
import DAGSLAM 
importlib.reload(DAGSLAM)

from DAGSLAM import dagslam

#m_vec gives the total number of categories for each multinomial variable
#helper function to infer loss types and generate m_vec for each column
def infer_type(df):
    loss_type=[]
    m_vec=[]

    for col in df.columns:
        x=df[col].dropna()
        unique_vals=x.unique()
        num_unique = len(unique_vals)

        #infer variable type by combination of dtype and cardinality
        if np.issubdtype(x.dtype, np.number):
            #numeric datatypes
            if num_unique == 2 and set(unique_vals).issubset({0,1}): #binary numeric variable
                loss_type.append("logistic")
                m_vec.append(1) # 1 "category"
            else: #continuous 
                loss_type.append("gauss")
                m_vec.append(1)
        else: #non-numeric
            if num_unique == 2:
                #binary categorical 
                loss_type.append("logistic")
                m_vec.append(1)
            else:
                #multi-class categorical
                loss_type.append("multi-logistic")
                m_vec.append(num_unique)

    return loss_type, m_vec

def run_dagslam(df, lambda1=0.03, max_iter=100, w_threshold=0.25): #changed lambda 1 0.03 ->0.1 w_threshold 0.25->0.3
    df_clean = df.dropna().copy()
    loss_type, m_vec =infer_type(df_clean)
    X=df_clean.values
    
    W_est = dagslam(X, loss_type=loss_type, m_vec=m_vec, lambda1=lambda1,max_iter=max_iter, w_threshold=w_threshold)
    return W_est

#draw graphs based on DAGSLAM weighted adjacency matrix
def draw_graph(W, output_path, node_labels=None,threshold=0):
    n = W.shape[0] # number of nodes
    G = nx.DiGraph() # initialise empty directed graph
    
    #initialise default node labels
    if node_labels is None:
        node_labels = [f"X{i}" for i in range(n)]

    #add nodes to digraph
    for i, name in enumerate(node_labels):
        G.add_node(i, label=name)

    #add edges for surviving weights (thresholding done during the dagslam phase)
    for i in range(n):
        for j in range(n): # for each possible edge 
            w=W[i,j]
            if abs(w)>threshold:
                G.add_edge(i, j, weight=w)

    plt.figure(figsize=(6,6))
    pos = nx.spring_layout(G, seed=0)
    nx.draw(G, pos, with_labels=True, labels={i: node_labels[i] for i in range(n)},
            node_size=800, font_size=8, arrowsize=10)
    plt.tight_layout()
    plt.savefig(out_path, dpi=150)
    plt.close()

In [24]:
from graphviz import Digraph
from pathlib import Path
import numpy as np

def draw_graphviz_dag(W, out_path, node_labels=None, threshold=0.0, engine="dot"):

    W = np.asarray(W)
    if W.ndim == 1:
        W = W.reshape(1, 1)

    n = W.shape[0]

    # Default labels use X0, X1,...
    if node_labels is None:
        node_labels = [f"X{i}" for i in range(n)]
    else:
        node_labels = list(node_labels)[:n]

    out_path = Path(out_path)
    g = Digraph(format="svg", engine=engine)

    g.attr(rankdir="LR")
    g.attr(
        "node",
        shape="ellipse",
        style="solid",
        color="black",
        fontname="Helvetica",   # or "Times New Roman" / "Palatino"
        fontsize="10",
    )
    g.attr(
        "edge",
        color="black",
        arrowsize="0.7",
    )

    # Add nodes
    for name in node_labels:
        g.node(name, label=name)

    # Add edges for weights above threshold
    for i, src in enumerate(node_labels):
        for j, tgt in enumerate(node_labels):
            w = W[i, j]
            if abs(w) > threshold:
                # You can optionally add weight as label=str(round(w, 2))
                g.edge(src, tgt)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    g.render(filename=out_path.with_suffix("").as_posix(), cleanup=True)

In [25]:
#scoring utility function given two adjacency matricies
def score_graph(W_est, W_true, labels_est, labels_true):
    #number of variables
    p = W_est.shape[0]

    #node orderings
    labels_est = list(labels_est)
    labels_true = list(labels_true)
    common = sorted(set(labels_est) & set(labels_true))

    #map ids
    idx_est = [labels_est.index(v) for v in common]
    idx_true = [labels_true.index(v) for v in common]

    W_est_aligned = np.asarray(W_est)[np.ix_(idx_est, idx_est)]
    W_true_aligned = np.asarray(W_true)[np.ix_(idx_true, idx_true)]

    est = (W_est!=0).astype(int)
    true = (W_true !=0).astype(int)

    #true positive, false positive, false negative, true negative
    tp = np.sum((est==1) & (true==1))
    fp = np.sum((est==1) & (true == 0))
    fn = np.sum((est==0) & (true == 1))
    tn = np.sum((est==0) & (true == 0))

    #structural hamming distance, true positive rate, false positive rate
    shd = fp + fn
    tpr = tp/(tp+fn) if (tp+fn) > 0 else np.nan
    fpr = fp/(fp+tn) if (fp + tn)>0 else np.nan
    fdr = fp/(tp+fp) if (tp+fp)>0 else np.nan

    #store scores in dictionary format for each 'experiment'
    return dict(TP=int(tp), FP=int(fp), FN=int(fn), TN=int(tn), SHD=int(shd), TPR = tpr, FPR = fpr, FDR= fdr)

In [26]:
#recurse over all csv datasets and run DAGSLAM
csv_files = sorted(cp_root.rglob("*.csv"))
print(f"Found {len(csv_files)} CSV files")
results = []

for csv_path in csv_files:
    rel = csv_path.relative_to(cp_root)

    #we only examine those with known ground truths i.e with _truth
    if csv_path.stem.endswith("_truth"):
        continue

    #expected ground truth path
    truth_path = csv_path.with_name(csv_path.stem + "_truth.csv")
    if not truth_path.exists():
        print("  Skipped (no ground-truth file)")
        continue

    print(f"Processing: {rel}")

    try:
        df = pd.read_csv(csv_path)
        if df.empty:
            print("  Skipped (empty file)")
            continue

        # Run DAGSLAM on this dataset
        W_est = run_dagslam(df)

        #Output schema scenario__file__dagslam.png
        parts = rel.parts           
        scenario = parts[0] if len(parts) > 1 else "root"
        name_no_ext = csv_path.stem

        out_name = f"{scenario}__{name_no_ext}__dagslam.png"
        out_path = output_dir / out_name

        # Save PNG
        #draw_graph(W_est, out_path, node_labels=list(df.columns))

        #use graphviz instead
        draw_graphviz_dag(W_est, out_path, node_labels=list(df.columns), threshold=0.0)
        print(f"  Saved graph to {out_path.relative_to(project_root)}")

        #load ground truth and score
        gt_df = pd.read_csv(truth_path)
        gt_df.index.name = None
        gt_df.columns.name = None

        W_true = gt_df.to_numpy()
            
        # compute scores
        metrics = score_graph(W_est, W_true, labels_est=list(df.columns), labels_true=list(gt_df.columns))
        print("metrics computed")
        print(metrics)
        metrics.update(
            dict(
                scenario=scenario,
                dataset=name_no_ext,
                algo="dagslam"
            )
        )
        results.append(metrics)
        print(f"  SHD={metrics['SHD']}, TPR={metrics['TPR']:.3f}, FDR={metrics['FDR']:.3f}")

    except Exception as e:
        print(f"  ERROR on {rel}: {e}")

scores_df = pd.DataFrame(results)

Found 171 CSV files
  Skipped (no ground-truth file)
  Skipped (no ground-truth file)
  Skipped (no ground-truth file)
  Skipped (no ground-truth file)
  Skipped (no ground-truth file)
  Skipped (no ground-truth file)
  Skipped (no ground-truth file)
  Skipped (no ground-truth file)
  Skipped (no ground-truth file)
  Skipped (no ground-truth file)
  Skipped (no ground-truth file)
  Skipped (no ground-truth file)
  Skipped (no ground-truth file)
  Skipped (no ground-truth file)
  Skipped (no ground-truth file)
Processing: casual_effect/device_failure_data.csv
iter:0
rho:1.0
loss=1007267.30610992
loss=1007267.30610992
loss=1007267.30610992
loss=1007267.30610992
loss=1007267.30610992
loss=1007267.30610992
loss=1007267.30610992
loss=1007267.30610992
loss=1007267.30610992
loss=1007267.30610992
loss=1007267.30610992
loss=1007267.30610992
loss=1007267.30610992
loss=1007267.30610992
loss=1007267.30610992
loss=1007267.30610992
loss=1007267.30610992
loss=1007267.30610992
loss=1007267.30610992
loss=1007267.30610992
loss=1007267.30610992
loss=1007267.30610992
loss=1017324.3379617037
loss=1007276.8507611175
loss=1007267.003036272
loss=1007266.7845597798
loss=1007266.4181043891
loss=1007266.0300447727
loss=1007265.2379064964
loss=1007260.866783478
loss=1007246.776083099
loss=1007185.6248030893
loss=1006891.8399333246
loss=1006128.3760008046
loss=1004647.3980108136
loss=999219.8932416352
loss=992698.9699173283
loss=969775.4274532719
loss=956039.6499102265
loss=951053.5370287594
loss=950640.9218210299
loss=950626.27187579
loss=950615.5981688545
loss=950581.5380510557
loss=950406.0027028495
loss=949703.3615857903
loss=948114.5570498169
loss=944582.0571111953
loss=941003.733814949
loss=924608.0308987491
loss=924512.2120885868
loss=924494.1112896544
loss=924415.89201573
loss=925769.465447843
loss=924400.2794356107
loss=924844.3744293335
loss=924370.924880407
loss=924373.4089349924
loss=924335.7333091757
loss=958752.6475128089
loss=924325.1185922266
loss=932049.7165036639
loss=924320.3783404804
loss=928304.732959997
loss=924315.5905950154
loss=926167.3340185654
loss=924312.9718545735
loss=924999.0141858237
loss=924311.9486231176
loss=924593.524366121
loss=924311.4811108332
loss=924471.9309651348
loss=924311.1860764348
loss=924409.2663878488
loss=924310.9803742423
loss=924368.8896951553
loss=924310.8289638514
loss=924342.9582959486
loss=924310.7048296033
loss=23797108564848.72
loss=924328.9074771185
loss=924327.9346158105
loss=924324.043170676
loss=924321.7137290611
loss=92473111.47018097
loss=9842154.769092493
loss=2096196.5502145926
loss=1064903.1301608123
loss=928062.7439570299
loss=920767.0847504553
loss=916672.8174051944
loss=911271.5284611683
loss=907530.9456546847
loss=905186.3589456155
loss=903590.5183186937
loss=902214.6041353535
loss=897603.5802689004
loss=893036.4819780886
loss=900039.8629057594
loss=892453.5033368048
loss=908031.7739906759
loss=892297.1199606092
loss=889698.8557133187
loss=890558.7120359762
loss=889186.4180986071
loss=891754.6250334199
loss=888593.15082317
loss=888059.6246940889
loss=887195.2560971408
loss=885929.8676439775
loss=881423.1821812807
loss=916040.6762178139
loss=879616.9477612248
loss=880556.1441378103
loss=879715.7912554316
loss=879616.9477612248
loss=879959.7094158836
loss=879622.2337291933
loss=879569.5052770638
loss=879034.5261587098
loss=878305.3698316205
loss=879261.4422442324
loss=877822.8393315583
loss=877364.1583478199
loss=876732.6555666759
loss=876661.6411034827
loss=876400.8311543319
loss=876181.0713949892
loss=876026.0431052588
loss=875541.7120369823
loss=877847.63004682
loss=875448.5062025408
loss=889307.1879312957
loss=875848.3452064835
loss=875426.8409662445
loss=875676.8678136348
loss=875415.738584642
loss=875575.6665576177
loss=875409.8624888816
loss=875514.987037099
loss=875407.5991150428
loss=875152.5950222592
loss=875506.4566387846
loss=874959.2718127655
loss=879843.6721107331
loss=874869.4696342681
loss=876682.8255636622
loss=874835.8973974378
loss=885991.9717532933
loss=875194.489061754
loss=874825.7451037619
loss=875048.5806716376
loss=874819.8859822837
loss=874960.1602122366
loss=874816.5212898403
loss=874906.278563283
loss=874814.639727551
loss=874828.4669223245
loss=874814.261766064
loss=875231.9488216164
loss=874860.1427710963
loss=874817.1678367794
loss=874813.3775707012
loss=874665.1999770992
loss=874665.7352501785
loss=874648.0657282565
loss=874652.503407559
loss=874645.9519005279
loss=874676.9126284624
loss=874646.1002898492
loss=874645.1075135998
loss=874702.1057355806
loss=874639.9503431625
loss=874633.3565741536
loss=874591.6824782698
loss=874668.567824689
loss=874589.0567270544
loss=874573.6321120133
loss=874633.3181293398
loss=874566.2511861523
loss=874546.3007947257
loss=874516.3176501697
loss=874447.547999575
loss=874292.8738478749
loss=874224.1155394753
loss=874190.4045838239
loss=875610.821525411
loss=874188.7697060034
loss=874784.7127496547
loss=874187.9225769116
loss=874265.7904698357
loss=874186.6822914337
loss=874525.0240296393
loss=874179.9863435619
loss=874281.6948087151
loss=874176.4721700614
loss=874126.3812111566
loss=879769.7635975179
loss=874134.5592291602
loss=874106.4339688746
loss=873979.1147003073
loss=873854.3055379308
loss=873847.0178081521
loss=873879.7901131519
loss=873845.9018092902
loss=873828.7336566515
loss=873765.4714736572
loss=873727.8717072001
loss=873670.5409187743
loss=873639.4662699485
loss=873629.984068189
loss=873636.2462996083
loss=873616.9677004827
loss=873619.88054522
loss=873577.179629805
loss=873598.6059775827
loss=873495.6837726098
loss=873391.6478144737
loss=873406.0218794486
loss=874780.5337230321
loss=873392.574054789
loss=873351.5182091832
loss=873347.4524814467
loss=873357.2529954555
loss=873333.0060557838
loss=873385.5933048298
loss=873325.3290294759
loss=873351.6158965443
loss=873319.1364230027
loss=873336.0851881038
loss=873315.7224706564
loss=873324.0249213232
loss=873316.2174637815
loss=873317.4151980238
loss=873314.1839292987
loss=873317.3100710167
loss=873313.7137199611
loss=873313.6281673617
loss=873313.4272353015
loss=873313.6222946774
loss=873313.5424818109
loss=873313.5146293702
loss=873313.6854848394
loss=873314.0162336619
loss=873314.1826840355
loss=873315.0007577522
loss=873314.7884700226
loss=873314.9990054311
loss=873314.9257206016
loss=873315.4796682657
loss=873315.1435436733
loss=873315.1249475748
loss=873315.0834657243
loss=873314.8471318118
loss=873313.973280555
loss=873311.2525473643
loss=873310.1209629042
loss=873308.5201170716
loss=873305.3315305106
loss=873302.5505887247
loss=873293.6290016464
loss=873288.0372240441
loss=873277.5102722015
loss=873084.443388002
loss=872706.7565495981
loss=872089.4126846843
loss=869632.339187827
loss=868712.2390318622
loss=868488.3539581769
loss=868472.701964649
loss=868464.691331757
loss=868419.777977389
loss=868314.1313984813
loss=868066.1297476549
loss=867575.5042262526
loss=866913.8340350608
loss=865482.8988426658
loss=865022.596124737
loss=864521.7391628097
loss=870840.5252434579
loss=864482.3856020762
loss=864484.4100806424
loss=864352.4428791805
loss=864235.4514173823
loss=864226.0096344958
loss=864194.425552964
loss=864318.194449392
loss=864191.526100885
loss=864109.8746838379
loss=863815.722722938
loss=863466.0815580231
loss=863962.5447627596
loss=863096.1763925328
loss=868577.7842411714
loss=863637.3872802356
loss=863072.1949192444
loss=869734.9814869766
loss=863059.48019405
loss=862740.1650562778
loss=862457.1587681287
loss=862169.052174772
loss=861821.7879484376
loss=861804.2295386933
loss=861429.332443404
loss=864902.2818361098
loss=861209.4159126302
loss=860853.4072245437
loss=860714.8248959321
loss=860509.2608770481
loss=860337.1262746949
loss=860312.3106414091
loss=861009.376528874
loss=860307.8012227757
loss=860284.4897408917
loss=860314.3723303438
loss=860221.4928100945
loss=860422.268680283
loss=860221.8907288593
loss=860348.1001932309
loss=860177.2604045797
loss=860156.7882975634
loss=860144.455771485
loss=860152.6655450489
loss=860137.2233043592
loss=860123.5553915628
loss=860113.3559035766
loss=860055.6936761072
loss=859926.0085533343
loss=863439.1520774284
loss=860036.6210006513
loss=859929.2165641398
loss=859881.1388317896
loss=859778.0777673894
loss=859760.6248720271
loss=859724.9884163064
loss=859699.6343130772
loss=859693.9654554685
loss=859687.192245142
loss=859675.414606666
loss=859680.0421795356
loss=859672.4808574992
loss=859663.0505692366
loss=859657.9861492197
loss=859651.3544591115
loss=860044.702778867
loss=859646.8614383347
loss=859796.6090177788
loss=859645.471787088
loss=859664.6461404978
loss=859644.8386411086
loss=860163.0897823689
loss=859652.253503836
loss=859644.2483056824
loss=859681.7268698239
loss=859641.2204168652
loss=859635.6852693605
loss=859737.334838361
loss=859627.648152185
loss=859623.2588371987
loss=859620.2310977683
loss=859640.2543449996
loss=859618.4571435271
loss=859617.5973878101
loss=859619.2403184782
loss=859640.3309736559
loss=859620.339509301
loss=859619.5813004064
loss=859618.727150539
loss=859617.8885327392
loss=859618.042267305
loss=859618.187673957
loss=859618.3618153255
loss=859618.3595647772
loss=859618.2525695583
loss=859617.808000554
loss=859617.3892480426
loss=859616.811669958
loss=859614.6042739062
loss=859611.4421086068
loss=859610.5883415322
loss=859611.0837314907
loss=859610.5713970516
loss=859612.4909852353
loss=859609.5916530829
loss=859592.6266838823
loss=859556.1332097653
loss=859505.6466866367
loss=858822.1662873543
loss=858125.0888008901
loss=855937.882355238
loss=853989.9116537024
loss=852742.1748269495
loss=852614.6340706084
loss=852581.7127506887
loss=852565.6063437127
loss=852557.426089863
loss=852454.6494167087
loss=851975.9803802953
loss=852531.3692817842
loss=851788.1657989627
loss=851720.6546978279
loss=851304.2578632791
loss=851389.4358242643
loss=851109.9763585792
loss=851005.4335670401
loss=850962.9349876114
loss=851009.5905714934
loss=850935.3788592961
loss=850914.7832186923
loss=850867.575816414
loss=851182.063868431
loss=850857.8849430074
loss=850851.2767976621
loss=850829.2198608407
loss=850832.5240231873
loss=850828.1109737429
loss=850830.8228615425
loss=850825.9906170666
loss=850816.678155163
loss=850767.1047244312
loss=850975.186171342
loss=850779.3211979767
loss=850764.0856666041
loss=851103.4522343539
loss=850766.2026869943
loss=850763.2059213525
loss=850757.9419218544
loss=850750.7707336397
loss=850742.9210528439
loss=850739.7808687708
loss=850737.8781049642
loss=850738.12714076
loss=850723.0541231479
loss=850696.3144896224
loss=850667.3556441596
loss=850865.1232962724
loss=850642.6059107617
loss=850905.377722942
loss=850656.9408625778
loss=850638.9922223889
loss=850704.4885405841
loss=850623.0343266309
loss=850774.6134915294
loss=850624.673545013
loss=850620.268925853
loss=850640.0996339559
loss=850618.7951690704
loss=850622.6294548644
loss=850617.1731342033
loss=850624.1532210411
loss=850610.7280709564
loss=850634.6801491211
loss=850605.2755727827
loss=850631.30700401
loss=850605.0232940012
loss=850605.0432427072
loss=850604.7510909601
loss=850604.5406000413
loss=850604.3438761173
loss=850604.3323896126
loss=850604.2054475687
loss=850603.8956015025
loss=850604.075880992
loss=850603.616620506
loss=850603.5710467322
loss=850603.5665754547
loss=850603.5596175737
loss=850603.549980347
loss=850603.4880268887
loss=850603.3533583953
loss=850602.9970797005
loss=850602.8494883106
loss=850602.5619135672
loss=850602.3107317062
loss=850602.229096101
loss=850602.1737328774
loss=850602.0974438012
loss=850601.94763765
loss=850601.637854881
loss=850601.045521805
loss=850599.995352278
loss=850598.6576693871
loss=850598.7958890843
loss=850598.0482514406
loss=850597.2948461627
loss=850597.2906739492
loss=850597.4317517219
loss=850597.3728975878
loss=850597.3419537034
loss=850597.3266376022
h:3.994959674563148
######################################################
iter:1
rho:1.0
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=851604.8087973266
loss=850701.8257486023
loss=850604.8269705616
loss=850597.497413546
loss=850597.6927648693
loss=850597.5310771993
loss=850597.4852139817
loss=850597.4805557684
loss=850597.4785057455
h:26.179919847404392
######################################################
rho:10.0
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=852485.9063501785
loss=850773.6153961914
loss=850601.8692564125
loss=850597.3427877543
loss=850597.3337095974
loss=850597.3349310411
loss=850597.3405229355
loss=850597.3591052236
loss=850597.3634661257
loss=850597.3621505203
loss=850597.3704673656
loss=850597.9208232338
loss=850602.003925289
loss=850598.5581192505
loss=850600.8921746829
loss=850601.9535012656
loss=850601.8055672144
loss=850602.8439159348
loss=850601.8297576165
h:20.597831108566034
######################################################
rho:100.0
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=852202.4026204328
loss=850843.7946615932
loss=850610.659335013
loss=850597.3917451027
loss=850597.3353949313
loss=850597.3370492012
loss=850597.3447656727
loss=850597.3763554088
loss=850597.3825651438
loss=850597.3832413153
loss=850597.3904120575
loss=850597.4836020769
loss=850598.4373434335
loss=850603.9634742683
loss=850628.0867385245
loss=850614.1225927494
loss=850803.3482251879
loss=850623.5124744843
loss=850614.6282614318
loss=850610.6136115226
loss=850612.7405511047
loss=850610.4479001026
loss=850611.7965276795
loss=850610.6052568549
loss=850609.64705965
loss=850608.0267180769
loss=850607.0942428793
loss=850604.1291167771
loss=850606.4475201357
loss=850605.2381281079
loss=850605.4002472799
loss=850604.7515512198
loss=850602.8013204478
loss=850604.1574834393
loss=850603.3452283329
loss=850603.3034682178
loss=850602.6217370827
loss=850602.0466030866
loss=850601.8245393347
loss=850600.9072221862
loss=850601.4743142533
loss=850600.9456303666
loss=850601.2858545413
loss=850601.1445687265
loss=850600.881341781
loss=850600.4386848036
loss=850600.6879276035
loss=850600.415426643
loss=850600.2500642658
loss=850599.9062189747
loss=850600.1501198639
loss=850600.0249286111
loss=850599.9157127624
loss=850599.8207464424
loss=850599.4416099403
loss=850599.7448416984
loss=850599.6055490496
loss=850599.6273502349
loss=850599.5622881106
loss=850599.3959532059
loss=850599.5007508883
loss=850599.4353029564
loss=850599.4164664949
loss=850599.349691022
loss=850599.3860380272
loss=850599.3293734113
loss=850599.3569449194
loss=850599.3439883257
loss=850599.3315330672
loss=850599.298138906
loss=850599.3205041001
loss=850599.3101823678
loss=850599.3046105762
loss=850599.2944753756
loss=850599.3004548593
loss=850599.2956091982
loss=850599.2950495251
loss=850599.2929188095
h:6.247562554702524
######################################################
rho:1000.0
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=851961.0568069527
loss=850809.9019371258
loss=850608.5300501771
loss=850597.3841522607
loss=850597.3348738733
loss=850597.3364108038
loss=850597.3435224179
loss=850597.3759853907
loss=850597.3831659412
loss=850597.382750089
loss=850597.3849608761
loss=850598.3660559366
loss=850605.0487083201
loss=850599.6586633516
loss=850603.3474153345
loss=850604.413005197
loss=850603.7942228243
loss=850630.6630630115
loss=850609.193674402
loss=850604.7712449012
loss=850604.0313903639
loss=850603.9485957704
loss=850603.8426728129
loss=850603.8594511737
loss=850603.8470174272
loss=850603.7761734795
loss=850603.6859787046
loss=850603.5842361082
loss=850603.4163659523
loss=850603.2847026857
loss=850602.7896507636
loss=850603.1654199885
loss=850602.942790826
loss=850603.0545631577
loss=850602.9032445778
loss=850602.7877889785
loss=850602.2653288879
loss=850602.6703292569
loss=850602.4443362043
loss=850602.5758325973
loss=850602.4899687889
loss=850602.366251568
loss=850601.9801835256
loss=850602.2792228212
loss=850602.1110324163
loss=850602.1178908242
loss=850601.998776554
loss=850601.6741122616
loss=850601.9016974937
loss=850601.7433300749
loss=850601.6906986859
loss=850601.4814637101
loss=850601.6124480949
loss=850601.2854957036
loss=850601.5313940768
loss=850601.4318117027
loss=850601.3627071466
loss=850601.2153370619
loss=850601.188802037
loss=850601.0370477658
loss=850601.0648773824
loss=850600.9927539277
loss=850600.706348435
loss=850600.9274064865
loss=850600.8334157668
loss=850600.8081028601
loss=850600.6949550657
loss=850600.6864036649
loss=850600.5752618657
loss=850600.5754966713
loss=850600.4911177758
loss=850600.4389602902
loss=850600.3912014773
loss=850600.2567154155
loss=850600.3554718724
loss=850600.2892655447
loss=850600.3265537013
loss=850600.3030893529
loss=850600.2634306223
loss=850600.1738401814
loss=850600.2379581657
loss=850600.1889298041
loss=850600.1799726883
loss=850600.1311922827
loss=850600.1191961952
loss=850600.0608441646
loss=850600.0930973843
loss=850600.0616698033
loss=850600.0389801979
loss=850600.0085322959
loss=850599.7036709378
loss=850599.8881592578
loss=850599.9866407575
loss=850599.9742033032
loss=850599.9557230301
loss=850599.9427336077
loss=850599.8827909052
loss=850599.9318233979
loss=850599.914177007
loss=850599.9087619092
loss=850599.8877783255
loss=850599.8978701653
loss=850599.8785098174
loss=850599.8895671003
loss=850599.8769944307
loss=850599.8680228051
loss=850599.8298572919
loss=850599.8591440222
loss=850599.8415742796
loss=850599.8526619475
loss=850599.8463827327
loss=850599.8334353181
loss=850599.8287028652
loss=850599.8067908925
loss=850599.8222714713
loss=850599.8131553229
loss=850599.8177815243
loss=850599.8149507707
loss=850599.8124666762
loss=850599.8082096016
loss=850599.8105113066
h:7.496487803253592
######################################################
rho:10000.0
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=850597.3266376022
loss=851931.7109137992
loss=850805.4234224146
loss=850608.2469362448

/dcs/23/u2200504/thesis/envthesis/lib/python3.13/site-packages/scipy/linalg/_matfuncs.py:389: RuntimeWarning: overflow encountered in matmul
  eAw = eAw @ eAw
/dcs/23/u2200504/thesis/envthesis/lib/python3.13/site-packages/scipy/linalg/_matfuncs.py:389: RuntimeWarning: invalid value encountered in matmul
  eAw = eAw @ eAw

loss=1.5793732730277777e+20
loss=1.7408627974128455e+20
loss=2.0543360618091446e+20
loss=2.2846696921316426e+20
loss=4.12688399807212e+20
loss=2.4880309618497952e+20
loss=2.9163368250712896e+20
loss=3.44220162153845e+20
loss=3.469922905730881e+20
loss=1.5918465734106684e+24
loss=3.46326124037365e+20
loss=3.462069782032101e+20
loss=3.457319786954845e+20
loss=3.438573219268837e+20
loss=3.367641550493065e+20
loss=2.9381494124384164e+20
loss=2.799420872810209e+20
loss=1.9859417554907588e+20
loss=1.918585797957498e+20
loss=1.906171360145516e+20
loss=1.8994875164365265e+20
loss=1.8763798586047522e+20
loss=1.76740284985435e+20
loss=1.6316232467986206e+20
loss=1.572776959685295e+20
loss=1.5645800682420332e+20
loss=1.5499315153596016e+20
loss=1.4423351779382716e+20
loss=1.335583512771895e+20
loss=1.3005187332839021e+20
loss=1.2706927824635239e+20
loss=1.2687898666606146e+20
loss=1.2644280034476193e+20
loss=1.261909952088933e+20
loss=1.260514475659191e+20
loss=1.2666422387160901e+20
loss=1.2867549609512524e+20
loss=1.3110040007889597e+20
loss=1.3225279009783937e+20
loss=1.329267117259271e+20
loss=1.3264085957506518e+20
loss=1.3242163000382783e+20
loss=1.3146261164018893e+20
loss=1.307443344112815e+20
loss=1.2887083791731782e+20
loss=1.2842093671337645e+20
loss=1.2744554007029809e+20
loss=1.255408712448379e+20
loss=1.2365018382876857e+20
loss=1.2241187723221528e+20
loss=1.2299007631811445e+20
loss=1.2200441076936583e+20
loss=1.2223584544967438e+20
loss=1.2230320272856372e+20
loss=1.2225950299276159e+20
loss=1.2218464109047769e+20
loss=1.2214010132368605e+20
loss=1.218419918407461e+20
loss=1.2185741897116543e+20
loss=1.2187706625132613e+20
loss=1.2201629287540372e+20
loss=1.2210710607926767e+20
loss=1.221401969950966e+20
loss=1.2214975273190977e+20
loss=1.221139205729824e+20
loss=1.2213406004450851e+20
loss=1.2213293155862918e+20
loss=1.2211306683576694e+20
loss=1.2209591905846968e+20
loss=1.2205973176368454e+20
loss=1.2199830618114315e+20
loss=1.2189257750649609e+20
loss=1.2173446829634771e+20
loss=1.216583565069756e+20
loss=1.2167768373991955e+20
loss=1.2172058222991213e+20
loss=1.2175181842612929e+20
loss=1.2180931045758914e+20
loss=1.2188017559908418e+20
loss=1.2196858954542367e+20
loss=1.2194532038769086e+20
loss=1.2186346232532174e+20
loss=1.2186506770249526e+20
loss=1.2186106422274264e+20
loss=1.218391709490736e+20
loss=1.2178654135008467e+20
loss=1.217142901161634e+20
loss=1.2167012525462503e+20
loss=1.2165899838206596e+20
loss=1.2165792171652122e+20
h:inf
######################################################
rho:100.0
loss=140.10301689184692
loss=140.10301689184692
loss=140.10301689184692
loss=140.10301689184692
loss=140.10301689184692
loss=140.10301689184692
loss=140.10301689184692
loss=140.10301689184692
loss=140.10301689184692
loss=140.10301689184692
loss=140.10301689184692
loss=140.10301689184692
loss=140.10301689184692
loss=140.10301689184692
loss=140.10301689184692
loss=140.10301689184692
loss=140.10301689184692
loss=140.10301689184692
loss=140.10301689184692
loss=140.10301689184692
loss=140.10301689184692
loss=140.10301689184692
loss=140.15040268705522
loss=140.15040296220846
loss=140.14720606795834
loss=140.13924037772227
loss=140.13705990227334
loss=140.37416813307559
loss=142.7825378189169
loss=160.60210182666393
loss=241.599266281482
loss=259.9387506918302
loss=348.74375182771155
loss=1118.336632230482
loss=5111.214344425161
loss=49437.25996616074
loss=78753.07091990733
loss=246504.21251924467
loss=595114.6209818084
loss=1593759.9782422886
loss=4114118.5770135694
loss=16546510.112955147
loss=88809967.17733471
loss=133873244.259865
loss=400418380.5759733
loss=947363235.8626956
loss=2865470646.5396156
loss=10101553327.449944
loss=18963503603.34194
loss=56224046499.01499
loss=139634229008.0857
loss=371733659035.98505
loss=965034729983.6807
loss=2531421438746.8057
loss=6617532641235.694
loss=17326421309489.816
loss=45347212196382.47
loss=118711968975893.39
loss=310780558687784.25
loss=813391546402865.4
loss=2168437325058018.8
loss=9149964910017840.0
loss=2.1273794282620036e+16
loss=3.607891526883418e+16
loss=1.1103621249807962e+17
loss=2.7090222141096016e+17
loss=1.1851821131286945e+18
loss=5.124354640762718e+18
loss=7.78115313699786e+18
loss=2.2726205743925375e+19
loss=5.1030906081732714e+19
loss=1.1402935725754555e+20
loss=2.1983097560229862e+20
loss=5.678985773143422e+20
loss=3.213002306732114e+20
loss=3.960701844972234e+20
loss=4.5556091221303355e+20
loss=4.908419840511488e+20
loss=5.5232369553665026e+20
loss=5.547775603496418e+20
loss=3.992634320588821e+20
loss=3.6300584251946684e+20
loss=4.038956952963445e+20
loss=4.2040103497620573e+20
loss=4.7514957873687744e+20
loss=8.418099651516094e+20
loss=4.8680039335196964e+20
loss=5.587018135406783e+20
loss=6.075175286751531e+20
loss=5.992231581089829e+20
loss=5.421216296791232e+20
loss=4.8708428927022845e+20
loss=4.2311158082993757e+20
loss=3.9975620431426585e+20
loss=3.1810047969770766e+20
loss=2.7417660668281238e+20
loss=3.1544173992693373e+20
loss=3.7960951642988105e+20
loss=4.8435945571732895e+20
loss=4.547685124258679e+20
loss=4.507803058503861e+20
loss=4.398376317329537e+20
loss=4.188603714113108e+20
loss=3.9668947296607994e+20
loss=2.5343325244362896e+20
loss=4.0362800394805825e+20
loss=3.9006210212850736e+20
loss=4.072373721191474e+20
loss=4.2389627933680167e+20
loss=7.456854635721973e+20
loss=4.0751911475467125e+20
loss=4.425228213551419e+20
loss=4.212246429118094e+20
loss=4.2420668900160615e+20
loss=4.174054150775797e+20
loss=3.9741918709466314e+20
loss=3.5347137227946315e+20
loss=3.060479159158534e+20
loss=2.7112337995628056e+20
loss=1.576791379758929e+20
loss=1.9610417012277376e+20
loss=2.4222971222513982e+20
loss=5.1260158503064345e+20
loss=2.4931460761757637e+20
loss=2.967569313139398e+20
loss=3.2006656335876044e+20
loss=3.505386202376242e+20
loss=3.80205919343406e+20
loss=4.0840793714273105e+20
loss=4.238907270396834e+20
loss=4.3121291460041494e+20
loss=4.401004254428985e+20
loss=4.868595912663896e+20
loss=4.9947952776007936e+20
loss=5.171843218540432e+20
loss=5.2666948577989034e+20
loss=5.386233297724691e+20
loss=5.599132988470437e+20
loss=5.723855924070066e+20
loss=5.7109373051003535e+20
loss=5.73910823762217e+20
loss=5.7726554477378535e+20
loss=5.889722383785634e+20
loss=6.026172710408995e+20
loss=6.135157359919771e+20
loss=6.065973754027425e+20
loss=5.780193658613086e+20
loss=5.3322286819487135e+20
loss=4.954943956423124e+20
loss=4.615620627814228e+20
loss=4.1743114813707977e+20
loss=3.928015140515587e+20
loss=3.9612113074469025e+20
loss=4.065962377123783e+20
loss=7.331479818915333e+20
loss=4.1669397143614856e+20
loss=4.1232332950573934e+20
loss=3.5755776152519207e+20
loss=3.099798836600339e+20
loss=2.6645819815865667e+20
loss=2.7639152860885647e+20
loss=2.6555938220852888e+20
loss=2.4577350580977533e+20
loss=2.3824450473668516e+20
loss=2.3099353267069593e+20
loss=2.257741962748341e+20
loss=2.2360977596730822e+20
loss=2.2097423627133662e+20
loss=2.6628083819045162e+20
loss=2.4878402115399e+20
loss=2.4549628037301876e+20
loss=2.4986175649963265e+20
loss=2.594378182623416e+20
loss=2.6357257297269588e+20
loss=2.666857847927358e+20
loss=2.6682160918885e+20
loss=2.6669656099873184e+20
loss=2.7144117106642295e+20
loss=2.765054507780032e+20
loss=2.9478748820706994e+20
loss=3.216701829539057e+20
loss=3.6485367719617095e+20
loss=5.316233501632189e+20
loss=3.859025091520399e+20
loss=3.882520046550045e+20
loss=3.870180586298563e+20
loss=3.8524802201040545e+20
loss=3.8309132712434205e+20
loss=3.820127311400714e+20
loss=3.477389718011044e+20
loss=3.547101263716283e+20
loss=3.6094139024968443e+20
loss=3.801630262439569e+20
loss=3.9421894067214916e+20
loss=4.312028348555257e+20
loss=4.689999597955105e+20
loss=5.0103991779635534e+20
loss=4.790297979557207e+20
loss=4.7451022070668716e+20
loss=4.665609765585395e+20
loss=4.598105996433968e+20
loss=4.414808892811043e+20
loss=4.1847876596635455e+20
loss=3.995873807833878e+20
loss=4.1079685394769065e+20
loss=4.471110845986886e+20
loss=4.911935893108326e+20
loss=5.328760589387946e+20
loss=5.718456432423716e+20
loss=9.746111436145749e+20
loss=5.920153678225263e+20
loss=6.09486578114453e+20
loss=6.093804347706527e+20
loss=5.952292956923401e+20
loss=5.7213693559974514e+20
loss=5.349914394092664e+20
loss=5.003500873521214e+20
loss=5.0896419301144605e+20
loss=5.297651278000829e+20
loss=5.416543129358405e+20
loss=5.4590173904316616e+20
loss=5.569258354497456e+20
loss=5.6750585894505945e+20
loss=5.493762973600838e+20
loss=5.368083056873182e+20
loss=5.2842825752793285e+20
loss=5.242705496788823e+20
loss=5.199559986520292e+20
loss=5.190259109482516e+20
loss=5.2263614899095234e+20
loss=5.263383792539797e+20
loss=5.240863561898479e+20
loss=5.206300339617683e+20
loss=5.142394009522877e+20
loss=4.987280807422183e+20
loss=4.6603213572912054e+20
loss=4.229255409408737e+21
loss=4.6380375928330846e+20
loss=4.2953105464010356e+20
loss=4.089334596871599e+20
loss=4.049618359504707e+20
loss=4.0436494352472126e+20
loss=4.0230794085534086e+20
loss=3.921673092309965e+20
loss=3.740717007448348e+20
loss=3.4987158683760106e+20
loss=3.281058816471834e+20
loss=3.09423015058471e+20
loss=2.884566433506246e+20
loss=2.7169960328831182e+20
loss=2.5772156985457312e+20
loss=2.4766231408921333e+20
loss=2.3368698014531863e+20
loss=2.3157923089626176e+20
loss=2.278928521320872e+20
loss=2.238578132148294e+20
loss=2.1544151136687063e+20
loss=2.0538374211170763e+20
loss=2.0831098971777388e+20
loss=1.9052945276292864e+20
loss=1.8835503279622062e+20
loss=1.8760851553635238e+20
loss=1.8671835156167813e+20
loss=1.8104761983529347e+20
loss=1.7276970219677116e+20
loss=8.189439274343617e+20
loss=1.690879084577529e+20
loss=1.5798533245128514e+20
loss=1.500355453595077e+20
loss=1.479538949114735e+20
loss=1.4743440170146582e+20
loss=1.4629539464507921e+20
loss=1.440013982612532e+20
loss=1.4112078766675454e+20
loss=1.3871876133428583e+20
loss=1.381338103429214e+20
loss=1.3805492349690308e+20
loss=1.3880847726745803e+20
loss=1.3727271656702799e+20
loss=1.3619428037257028e+20
loss=1.3106567590954933e+20
loss=1.2362341468844972e+20
loss=1.1733797086849637e+20
loss=1.1633892680428318e+20
loss=1.1627433239863753e+20
loss=1.16892845936796e+20
loss=1.17453161651803e+20
loss=1.1828642053476513e+20
loss=1.1965000212583485e+20
loss=1.2201274988655201e+20
loss=1.2554252518195855e+20
loss=1.2956434225379194e+20
loss=1.3059115477186568e+20
loss=1.5378945222791987e+20
loss=1.3249859557265677e+20
loss=1.2926381250972176e+20
loss=1.2683022992410953e+20
loss=1.2596891151774944e+20
loss=1.263037416262194e+20
loss=1.2668543870144902e+20
loss=1.2784018056471567e+20
loss=1.3012476647997984e+20
loss=1.345734848850963e+20
loss=1.4023479016818885e+20
loss=1.4391675467074145e+20
loss=1.4512314622270734e+20
loss=1.4441551508361082e+20
loss=1.4283822967934058e+20
loss=1.407988428620196e+20
loss=1.3848675121897559e+20
loss=1.3831190631428833e+20
loss=1.4430205640572674e+20
loss=1.5044185347058457e+20
loss=1.8156107281393372e+20
loss=1.5901540082140788e+20
loss=1.593282106346982e+20
loss=1.62475406576026e+20
loss=1.667650446360593e+20
loss=1.6842883301004408e+20
loss=1.7983163192799376e+20
loss=1.70648749740481e+20
loss=1.5933090405567503e+20
loss=1.549957012325476e+20
loss=1.530467143605019e+20
loss=1.5114662557479404e+20
loss=1.4829538933678703e+20
loss=1.6053587959021037e+20
loss=1.655211824419567e+20
loss=1.8666993588285515e+20
loss=1.8621377574032982e+20
loss=1.866081371381667e+20
loss=1.8771132558616612e+20
loss=1.962633309138411e+20
loss=2.0797124203434882e+20
loss=2.1810948309595246e+20
loss=2.13673928884898e+20
loss=2.1083425141652606e+20
loss=2.0359692459449654e+20
loss=1.888883780495811e+20
loss=1.81063380561012e+20
loss=1.7852521658663463e+20
loss=1.7784282272390716e+20
loss=1.8607820078903388e+20
loss=1.7709772339635585e+20
loss=1.7701820639807498e+20
loss=1.7435840587820882e+20
loss=1.658035067880194e+20
loss=1.5999998664218103e+20
loss=1.6298764955527905e+20
loss=1.646744471788098e+20
loss=1.7355407735477325e+20
loss=2.0787149611270786e+20
loss=2.565958678649039e+20
loss=2.964299895559878e+20
loss=3.1064526509955187e+20
loss=3.108693342111112e+20
loss=3.030218204721265e+20
loss=2.9619063425447e+20
loss=2.9030960202931352e+20
loss=2.9215093891192065e+20
loss=3.3699930560220745e+20
loss=2.7419560598968572e+20
loss=3.0093076002604247e+20
loss=3.4733012860085194e+20
loss=3.712107989701725e+20
loss=3.756654689621428e+20
loss=3.6020822954289876e+20
loss=3.3955731882908556e+20
loss=3.1686804844429745e+20
loss=2.9005220655739175e+20
loss=2.6136369734583845e+20
loss=2.3392062716475172e+20
loss=2.1392206834939894e+20
loss=2.0805137388042066e+20
loss=2.070473884670152e+20
loss=4.017107992810806e+20
loss=1.8766254479592207e+20
loss=1.8536390921570333e+20
loss=1.891494356856796e+20
loss=1.881622910928853e+20
loss=1.813376345730249e+20
loss=1.9817558523660324e+20
loss=1.829939587086743e+20
loss=1.752346398758151e+20
loss=1.8849464524534304e+20
loss=2.2922301059215825e+20
loss=2.9094307658122713e+20
loss=3.667728638267059e+20
loss=3.7926867210226526e+20
loss=3.8145684153156606e+20
loss=3.804470436918152e+20
loss=3.78885130408393e+20
loss=3.7932543299855476e+20
loss=3.9673209042815484e+20
loss=4.3089155944196466e+20
loss=4.465458385336698e+20
loss=4.4546065214759115e+20
loss=4.432141939920762e+20
loss=4.387055076901306e+20
loss=4.265061204930506e+20
loss=4.075094041926409e+20
loss=3.658553520339e+20
loss=3.855775829475419e+20
loss=3.68525820193147e+20
loss=3.561579912081543e+20
loss=3.561672006034413e+20
loss=3.53551328993731e+20
loss=3.540047662749822e+20
loss=3.508990878518752e+20
loss=3.660676671953375e+20
loss=3.5782100322385e+20
loss=3.658982314677712e+20
loss=3.563937890871353e+20
loss=3.454150289592071e+20
loss=3.444375399309413e+20
loss=3.485954911961333e+20
loss=4.4540835389581505e+20
loss=4.253477910317437e+20
loss=4.633391669818735e+20
loss=4.760492069415074e+20
loss=4.8280676850748306e+20
loss=4.657736702355855e+20
loss=4.403597702582205e+20
loss=4.275257441538815e+20
loss=4.018411469653e+20
loss=3.9441678936061936e+20
loss=3.913024785142e+20
loss=3.8300977539557674e+20
loss=3.876123964795504e+20
loss=3.860859935281249e+20
loss=3.712825318316475e+20
loss=3.443820094593447e+20
loss=3.256373174534423e+20
loss=3.112528921401004e+20
loss=3.10190579725425e+20
loss=3.254397395415261e+20
loss=3.533742025561317e+20
loss=4.4273896689444756e+20
loss=3.853429900424864e+20
loss=4.046730917513544e+20
loss=4.15719481866264e+20
loss=4.344784156433735e+20
loss=4.4453894492605304e+20
loss=4.581367976323834e+20
loss=4.717784879253098e+20
loss=4.829322088898965e+20
loss=4.8775343764823074e+20
loss=4.9154032342821084e+20
loss=4.911634952102756e+20
loss=4.796148844260384e+20
loss=4.765672198889446e+20
loss=4.737891663624809e+20
loss=4.67567137266276e+20
loss=4.6088290813895154e+20
loss=4.507470155993871e+20
loss=4.421522605401398e+20
loss=4.440732828624514e+20
loss=4.651635605518409e+20
loss=4.891336484156346e+20
loss=4.903582518667925e+20
loss=4.735257038693655e+20
loss=3.698722778734464e+21
loss=4.683019706427255e+20
loss=4.216555351828605e+20
loss=3.201777749120648e+20
loss=2.356879772388507e+20
loss=2.069338912499669e+20
loss=1.9154733141516383e+20
loss=1.9150376334413418e+20
loss=2.0051129330765365e+20
loss=2.1013488567676168e+20
loss=2.2302523272631897e+20
loss=2.4666305736403347e+20
loss=2.6527522237463796e+20
loss=2.426754229358543e+20
loss=2.47843304470957e+20
loss=2.4777893977519427e+20
loss=2.4291315500345075e+20
loss=2.3682622305978968e+20
loss=1.9375849022276495e+20
loss=6.831677796491276e+20
loss=2.5126902907466567e+20
loss=2.1978498274043062e+20
loss=2.111700222848811e+20
loss=2.177766413840888e+20
loss=2.2505493397995566e+20
loss=2.3645123015394758e+20
loss=2.5792205000622886e+20
loss=2.6537536756436953e+20
loss=2.894079528748155e+20
loss=2.9222327639232853e+20
loss=2.9330988043026137e+20
loss=2.9553239890708025e+20
loss=2.3995960442221494e+20
loss=2.503756341736291e+20
loss=2.7547282344489812e+20
loss=2.7001835097827072e+20
loss=2.586009967413782e+20
loss=2.4518497162449637e+20
loss=2.544906461494284e+20
loss=2.644473030107693e+20
loss=2.7466283437224388e+20
loss=2.920160426062497e+20
loss=3.324197037091215e+20
loss=2.9067118855608504e+20
loss=3.0124199183709346e+20
loss=3.155190324176459e+20
loss=3.238289023115534e+20
loss=3.076520404937151e+20
loss=3.357827077582442e+20
loss=3.118423246019401e+20
loss=2.993878277995755e+20
loss=2.8196145150820608e+20
loss=2.9684458147632264e+20
loss=3.216309945147426e+20
loss=3.3928591267385226e+20
loss=3.6110069318792066e+20
loss=6.025187454179228e+20
loss=3.651536774381099e+20
loss=3.853491664252902e+20
loss=3.8211879784865386e+20
loss=3.588876769479667e+20
loss=3.3832827250599336e+20
loss=3.7718173613110565e+20
loss=3.2015099046142476e+20
loss=3.31730025016956e+20
loss=3.205618150216271e+20
loss=3.050305621322465e+20
loss=2.454160579785048e+20
loss=2.0078193056849717e+20
loss=1.898140730068829e+20
loss=2.3350692572792757e+20
loss=2.5391190372445412e+20
loss=2.7479141538788013e+20
loss=2.6795553366444992e+20
loss=2.6316574589774345e+20
loss=2.6102411326449766e+20
loss=2.6272493931503013e+20
loss=2.6786282114997043e+20
loss=2.816269729970332e+20
loss=2.954345263325244e+20
loss=2.7919394204658873e+20
loss=2.8161640513550084e+20
loss=2.600157787747494e+20
loss=2.3861615322034173e+20
loss=2.61426089901323e+20
loss=2.3010243623797175e+20
loss=2.0500670684862018e+20
loss=1.8833095092986374e+20
loss=1.8461667871935162e+20
loss=1.877613397226164e+20
loss=1.953255508766161e+20
loss=2.0788898185527257e+20
loss=2.210874785788937e+20
loss=2.4775445531335518e+20
loss=2.308446925098991e+20
loss=2.358608413581983e+20
loss=2.3116534535935354e+20
loss=2.1615864888830873e+20
loss=2.0151552073693993e+20
loss=1.8629246955393702e+20
loss=1.890594142391934e+20
loss=1.940816905894544e+20
loss=1.9903137431714064e+20
loss=2.0414669345180913e+20
loss=2.1277301965452742e+20
loss=2.248555129486192e+20
loss=2.4123476127147452e+20
loss=2.572194109469777e+20
loss=2.6615106944421898e+20
loss=2.6451258062659207e+20
loss=2.59769888335316e+20
loss=2.6127861692778565e+20
loss=2.5622306768417522e+20
loss=2.585264894979968e+20
loss=2.6840091492838657e+20
loss=2.7627303570712222e+20
loss=2.7163787941706056e+20
loss=4.908774505592016e+20
loss=2.9430639458254206e+20
loss=2.598929646171068e+20
loss=2.2899684936034546e+20
loss=2.047797407195138e+20
loss=1.8956606694168212e+20
loss=1.8710909061617333e+20
loss=3.634183516698361e+20
loss=1.825381750301732e+20
loss=1.917573905554279e+20
loss=2.9012159814529086e+20
loss=2.848358396134893e+20
loss=3.026613066700837e+20
loss=3.138331458873462e+20
loss=3.0163672319336605e+20
loss=9.300124515681917e+20
loss=3.9056604037476326e+20
loss=3.282302086922509e+20
loss=2.8502641175696818e+20
loss=2.4036934531064473e+20
loss=2.0207200485368185e+20
loss=2.0689173174445126e+20
loss=1.8790394981718236e+20
loss=2.2117981423866544e+20
loss=2.6932989391376148e+20
loss=2.7541254048263766e+20
loss=2.8934686387226473e+20
loss=3.0287176840565975e+20
loss=2.9569671846491364e+20
loss=2.7284697009766793e+20
loss=1.9203903073603826e+20
loss=2.4356054992140884e+20
loss=2.264587030865576e+20
loss=2.1623510869518048e+20
loss=2.06806982112929e+20
loss=1.8973662481902295e+20
loss=1.8071222405012642e+20
loss=1.8333217783411173e+20
loss=2.001982878666431e+20
loss=9.330622228330187e+20
loss=2.2109181423134304e+20
loss=2.5796509091665294e+20
loss=2.615051407476042e+20
loss=2.5555153526009142e+20
loss=2.5638081359192523e+20
loss=2.5342342687480588e+20
loss=2.4415233927381274e+20
loss=2.1947502914370178e+20
loss=2.3382402827730967e+20
loss=2.190439006459583e+20
loss=2.2093387545393752e+20
loss=2.300809808656192e+20
loss=2.5050428175775505e+20
loss=2.3041622916470296e+20
loss=2.676032049119437e+20
loss=2.6343373786868705e+20
loss=2.581150202555473e+20
loss=2.533819638660336e+20
loss=2.494010907159283e+20
loss=2.566618960059914e+20
loss=2.3566809410439807e+20
loss=2.330810998819229e+20
loss=2.623221573093519e+20
loss=2.712507951711166e+20
loss=2.6900988527842794e+20

/dcs/23/u2200504/thesis/recidivism-causal/code/dagslam/DAGSLAM Causal Bayesian Network Structure Learning of Mixed Type Data/_dagslam/DAGSLAM.py:104: RuntimeWarning: invalid value encountered in logaddexp
  * (np.logaddexp(0, M[..., j]) - X[..., j] * M[..., j])
/dcs/23/u2200504/thesis/envthesis/lib/python3.13/site-packages/numpy/linalg/linalg.py:2120: RuntimeWarning: invalid value encountered in slogdet
  sign, logdet = _umath_linalg.slogdet(a, signature=signature)

loss=584.0097065274559
loss=584.0095558333279
loss=584.008791887675
loss=584.0087414698055
loss=584.008497816654
loss=584.0082515038492
loss=584.0079635348511
loss=584.0078121889374
loss=584.0074555933846
loss=584.007688413449
loss=584.0078032050444
loss=584.007847104019
loss=584.0078628506478
loss=584.007876448669
loss=584.0078532681534
loss=584.959991402057
loss=584.0078294188544
loss=584.0075693377928
loss=584.0071124888232
loss=584.0119581775326
loss=584.0071723199163
loss=584.0067312837384
loss=584.0065951177253
loss=584.0065588286086
loss=584.0065761175621
loss=584.0066347128776
loss=584.0066760943241
loss=584.0070154224321
loss=584.0075031829094
loss=584.0066102740668
loss=584.007308494477
loss=584.0080101661373
loss=584.008028617389
loss=584.0158047442179
loss=584.0081764286348
loss=584.007351796043
loss=584.006473297316
loss=584.0052052304966
loss=584.0056696446978
loss=584.0056528212227
loss=584.00564747341
loss=584.0056842123919
loss=584.0058184825392
loss=584.0061495308316
loss=584.0063951635202
loss=584.006440374789
loss=584.0070504911494
loss=584.0067231324405
loss=584.0064790001629
loss=584.0062932487783
loss=584.0060104875944
loss=584.005779686412
loss=584.0056666528568
loss=584.0055087874435
loss=584.0052591707422
loss=584.0050599726889
loss=584.0052105454452
loss=584.0050027311653
loss=584.0042551345665
loss=584.0027357622365
loss=583.9983537373536
loss=583.9974966719699
loss=583.9980022173542
loss=583.9976339289461
loss=583.9966063606319
loss=583.9960747767198
loss=583.9963354170112
loss=583.996481397896
loss=583.9962753437126
loss=583.9956311665082
loss=583.9950763048272
loss=583.9948206083361
loss=583.9949685262972
loss=583.994963407284
loss=583.9949809059502
loss=584.0388567207436
loss=583.9951027183661
loss=583.9950328391651
loss=584.9994263690799
loss=583.9950681840791
loss=583.9948232852298
loss=583.9944686897749
loss=583.9919038201931
loss=583.9923300453482
loss=583.9925489767603
loss=583.9921618194252
loss=583.9917266315721
loss=583.9917571576614
loss=583.990289146855
loss=583.9905736713059
loss=583.9901924953638
loss=583.9903022539602
loss=583.9887590839509
loss=583.9897158094865
loss=583.9892951110744
loss=583.9893546479698
loss=583.9893799445205
loss=583.989465623804
loss=583.9893849521238
loss=583.988682163029
loss=583.987066477985
loss=583.9845005442028
loss=583.9768483536941
loss=583.9821677400345
loss=583.9859060049115
loss=583.9804291731028
loss=583.9802614361615
loss=583.9793158062834
loss=583.9757703214515
loss=583.9659836234595
loss=583.9697688912314
loss=583.9662350886732
loss=583.9654522670752
loss=583.9645337973927
loss=583.9651032911171
loss=583.9646149423272
loss=583.9655153213038
loss=583.9649270792919
loss=583.9647508450983
loss=583.9647325189737
loss=583.9646599512737
loss=583.9643937212587
loss=583.9636907813438
loss=583.9635223312732
loss=583.963222923606
loss=583.9612055601275
loss=583.9579211357064
loss=583.9594641104142
loss=583.9580377835676
loss=584.3633084248769
loss=583.9580173366506
loss=583.9572401299249
loss=583.9564685679333
loss=583.9563014909933
loss=583.9564991627589
loss=583.9566284859357
loss=583.9569368629061
loss=583.9567663037361
loss=583.9567474955766
loss=583.9566583511946
loss=583.9563676276932
loss=583.9560473446883
loss=583.9558196501329
loss=583.9553568234785
loss=583.9543795108822
loss=583.9527229824853
loss=583.9503665825999
loss=583.9486416597684
loss=583.9486377040301
loss=583.9496779788786
loss=583.9496408074413
loss=583.9496456448727
loss=583.9497010779727
loss=583.9498224727687
loss=583.950025959193
loss=583.9500327433261
loss=583.9500195198073
loss=583.9500231451525
h:2.5098708289446456e+16
######################################################
iter:1
rho:1.0
loss=583.9500231451525
loss=583.9500231451525
loss=583.9500231451525
loss=583.9500231451525
loss=583.9500231451525
loss=583.9500231451525
loss=583.9500231451525
loss=583.9500231451525
loss=583.9500231451525
loss=583.9500231451525
loss=583.9500231451525
loss=583.9500231451525
loss=583.9500231451525
loss=583.9500231451525
loss=583.9500231451525
loss=583.9500231451525
loss=583.9500231451525
loss=583.9500231451525
loss=583.9500231451525
loss=583.9500231451525
loss=583.9500231451525
loss=583.9500231451525
loss=591.6108975146495
loss=591.6136100421035
loss=591.6244649615434
loss=591.6679615932885
loss=591.8431793840364
loss=591.9763115845499
loss=609.3580786717168
loss=646.1792091311622
loss=761.6739839426668
loss=1078.1952966221031
loss=1764.1968748328711
loss=4180.339707235203
loss=16581.13962567363
loss=417319.3084836002
loss=554701.7062698909
loss=1945822.982788691
loss=4606990.571539895
loss=12582477.366751704
loss=32459051.404053777
loss=85489448.51288307
loss=223306781.14575535
loss=585091716.1508728
loss=1531259545.865481
loss=4009561620.9914856
loss=10496777799.833326
loss=27482263086.530598
loss=71949464180.91931
loss=188369575514.45486
loss=493147866188.53345
loss=1291078124606.2932
loss=3379903541274.575
loss=8848035957052.037
loss=23158278646735.0
loss=60592047753929.04
loss=158365309545148.28
loss=412884072347419.06
loss=1070003639546884.1
loss=2740456545248683.0
loss=6899431898012399.0
loss=1.6851211631374176e+16
loss=3.767757609703855e+16
loss=9.326819160240835e+16
loss=1.2443522862411242e+17
loss=1.4583482772809126e+17
loss=1.6460965824952915e+17
loss=2.2762428573632947e+17
loss=2.0384040129291366e+17
loss=1.875561117213538e+17
loss=1.619985942479072e+17
loss=1.4378786700323944e+17
loss=1.4328420096032853e+17
loss=1.468635857296531e+17
loss=1.498500147576433e+17
loss=1.527634904218e+17
loss=1.5329120188584774e+17
loss=1.5407384910805312e+17
loss=1.5549645874856515e+17
loss=1.5999423141971606e+17
loss=1.659992657672388e+17
loss=1.797855046992564e+17
loss=1.7138657403710026e+17
loss=1.7798194767719523e+17
loss=1.8170949103632918e+17
loss=1.8025298500866653e+17
loss=1.7714504602304742e+17
loss=1.7874579907509357e+17
loss=1.8216534161393674e+17
loss=1.7970672905845907e+17
loss=1.7684369593367354e+17
loss=1.677226715453201e+17
loss=1.564661490465365e+17
loss=1.3364123213333949e+17
loss=1.323891797725231e+17
loss=1.3336181887793557e+17
loss=1.2983708914627747e+17
loss=1.2810668718507312e+17
loss=1.257861389552266e+17
loss=1.2439983597781363e+17
loss=1.2293163941884163e+17
loss=1.2280881505590102e+17
loss=1.4747077526587875e+17
loss=1.2623745338158976e+17
loss=1.281649334465899e+17
loss=1.3477212606763011e+17
loss=1.462694582516846e+17
loss=1.5740258889445696e+17
loss=1.5261348605850122e+17
loss=1.516708290799844e+17
loss=1.5093262124102678e+17
loss=1.5058529211795814e+17
loss=1.5061597319470333e+17
loss=1.501322327264478e+17
loss=1.4936479875770166e+17
loss=1.4950409255058058e+17
loss=1.5012893835185635e+17
loss=1.4983836118739123e+17
loss=1.494005071133864e+17
loss=1.4792819452281597e+17
loss=1.464452009147563e+17
loss=1.4928981162116614e+17
loss=1.4954351719742538e+17
loss=1.5356618177777555e+17
loss=1.620583464494876e+17
loss=1.704396718069243e+17
loss=1.8118345907857043e+17
loss=1.7523384224649197e+17
loss=1.7584639425239456e+17
loss=1.7512801938030995e+17
loss=1.7397235972126266e+17
loss=1.7317064412816006e+17
loss=1.6989729608682822e+17
loss=1.7108522466415677e+17
loss=1.7421369107425114e+17
loss=1.7365900693386493e+17
loss=1.912195297654636e+17
loss=1.8507397800420378e+17
loss=1.841680830648093e+17
loss=1.8492814383472685e+17
loss=1.8304232365182298e+17
loss=1.847598167587951e+17
loss=1.8484141726872813e+17
loss=1.8506896550271712e+17
loss=1.850863957537283e+17
loss=1.8447165585572333e+17
loss=1.8266068136366e+17
loss=1.804493307587138e+17
loss=1.7711879596352864e+17
loss=1.7277184491539254e+17
loss=1.6799380860530352e+17
loss=1.529027834843932e+17
loss=1.470593132320534e+17
loss=1.4993150029291616e+17
loss=1.4421606276250163e+17
loss=1.4336460734809411e+17
loss=1.4407243691696443e+17
loss=1.4471667662894698e+17
loss=1.4385034987815266e+17
loss=1.4807717801020925e+17
loss=1.44002741737141e+17
loss=1.4254002053363517e+17
loss=1.4175721611184771e+17
loss=1.4157548958673302e+17
loss=1.4173325039975155e+17
loss=1.4336566435591149e+17
loss=1.479156363931285e+17
loss=1.4373180859507283e+17
loss=1.4538853197125837e+17
loss=1.4615707848378512e+17
loss=1.4668146022090755e+17
loss=1.4709107537952493e+17
loss=1.4692726017109574e+17
loss=1.464523403799419e+17
loss=1.4520613123863974e+17
loss=1.4225046090476685e+17
loss=1.3906404790648918e+17
loss=1.3590095575744693e+17
loss=1.3811989716040934e+17
loss=1.3510495609912493e+17
loss=1.3444137104358998e+17
loss=1.353213027427124e+17
loss=1.3620920718795955e+17
loss=1.3706226925256848e+17
loss=1.3681402260719018e+17
loss=1.3568583552394693e+17
loss=1.3475885565453435e+17
loss=1.320822932983039e+17
loss=1.3268528065057843e+17
loss=1.3373803444715466e+17
loss=1.3447556462672173e+17
loss=1.3616342422326362e+17
loss=1.4217233327462922e+17
loss=1.4186639279537275e+17
loss=1.4194344464495677e+17
loss=1.4258183280906326e+17
loss=1.4293363898896734e+17
loss=1.4331628479829709e+17
loss=1.4338883422376576e+17
loss=1.4403688401376395e+17
loss=1.4540623126648682e+17
loss=1.460875682324692e+17
loss=1.4819150647213475e+17
loss=1.4996118286441466e+17
loss=1.531781774483897e+17
loss=1.5324962431917587e+17
loss=1.524184413180388e+17
loss=1.509897949531942e+17
loss=1.4838003790501206e+17
loss=1.4937899657221782e+17
loss=1.4738984947264896e+17
loss=1.4580170696229142e+17
loss=1.4512677707075104e+17
loss=1.442792544325001e+17
loss=1.4303829543020437e+17
loss=1.4191979002192336e+17
loss=1.4165869199846416e+17
loss=1.417828025402552e+17
loss=1.4157880450158312e+17
loss=1.4182881898696134e+17
loss=1.4341102094213478e+17
loss=1.4481171228393114e+17
loss=1.4749979790324144e+17
loss=1.4822973787525123e+17
loss=1.472198164124044e+17
loss=1.4540993680872365e+17
loss=1.4468469908256842e+17
loss=1.4400025522446406e+17
loss=1.471280039993357e+17
loss=1.491477601285577e+17
loss=1.5248765966932787e+17
loss=1.5453064090565648e+17
loss=1.613151965774753e+17
loss=1.653051603121263e+17
loss=1.657415842996052e+17
loss=1.6536350763880934e+17
loss=1.6446390323780042e+17
loss=1.6417156720647014e+17
loss=1.648313632561998e+17
loss=1.6781867039933706e+17
loss=1.72063229174261e+17
loss=1.696621176142369e+17
loss=1.691558856635092e+17
loss=1.67877549296059e+17
loss=1.676991061538415e+17
loss=1.6969301368742954e+17
loss=1.6797454990191184e+17
loss=1.6836896109638768e+17
loss=1.685752115416757e+17
loss=1.6858808578767264e+17
loss=1.6814626621755347e+17
loss=1.6766737049892995e+17
loss=1.6603448682884918e+17
loss=1.647184271839894e+17
loss=1.635956328527767e+17
loss=1.6331379064080368e+17
loss=1.6249673231785382e+17
loss=1.6204194275070832e+17
loss=1.6271870424023955e+17
loss=1.6405940673107728e+17
loss=1.652073664397696e+17
loss=1.6638931135593926e+17
loss=1.6728383704104422e+17
loss=1.6849274369100637e+17
loss=1.691403267731907e+17
loss=1.6866610502875907e+17
loss=1.6797554228863526e+17
loss=1.6706159959587504e+17
loss=1.6420107577050938e+17
loss=1.6010426118837264e+17
loss=1.5802938325588842e+17
loss=1.553082620937386e+17
loss=1.5427566130282e+17
loss=1.6148879815306938e+17
loss=1.5409548599919386e+17
loss=1.527874078585173e+17
loss=1.520462143053011e+17
loss=1.5201924385539088e+17
loss=1.513293551852279e+17
loss=1.4835911291335123e+17
loss=1.4646832666158358e+17
loss=1.4442785341266736e+17
loss=1.419745465860585e+17
loss=1.4156236951862336e+17
loss=1.4162711740051954e+17
loss=1.4080747008564738e+17
loss=1.4072376662881789e+17
loss=1.4146801998184075e+17
loss=1.4296553114774418e+17
loss=1.4379243451770464e+17
loss=1.4302101612015166e+17
loss=1.393784640814873e+17
loss=1.3790592940839968e+17
loss=1.3806721814745971e+17
loss=1.3808130766060083e+17
loss=1.381128202794567e+17
loss=1.382515582090844e+17
loss=1.3848374076390922e+17
loss=1.4352305966126315e+17
loss=1.39534315744916e+17
loss=1.3998939713556118e+17
loss=1.40651348254131e+17
loss=1.4143741063173053e+17
loss=1.4242748374024926e+17
loss=1.4406823474599918e+17
loss=1.4660498825375715e+17
loss=1.453360186213793e+17
loss=1.432145019969078e+17
loss=1.4136522524853149e+17
loss=1.3998118318252576e+17
loss=1.3720815828059136e+17
loss=1.3725331542429472e+17
loss=1.3923627913195878e+17
loss=1.4083912418266198e+17
loss=1.4185932719575246e+17
loss=1.3972787512380186e+17
loss=1.3700417375972458e+17
loss=1.3501264431307552e+17
loss=1.3021789275723781e+17
loss=1.2856707328683906e+17
loss=1.2960797655897555e+17
loss=1.3070313556676317e+17
loss=1.3307909314523483e+17
loss=1.3786883459231536e+17
loss=1.3697385868724112e+17
loss=1.363517335050674e+17
loss=1.360559752243835e+17
loss=1.3576171605772272e+17
loss=1.3558831649743067e+17
loss=1.3542059247115517e+17
loss=1.3528543576879229e+17
loss=1.3527183796783925e+17
loss=1.3523314642395531e+17
loss=1.3533441123930768e+17
loss=1.3556016794659267e+17
loss=1.356281755711541e+17
loss=1.3549159293809834e+17
loss=1.3520859363601298e+17
loss=1.345333640520871e+17
loss=1.3346615521363702e+17
loss=1.3189259909887896e+17
loss=1.3072283196644573e+17
loss=1.3061671877693845e+17
loss=1.309874028238561e+17
loss=1.3166823777836773e+17
loss=1.3373960501617542e+17
loss=1.3468133658775317e+17
loss=1.3439080510946286e+17
loss=1.343335335724824e+17
loss=1.3417083419244139e+17
loss=1.3395825806329762e+17
loss=1.3261413225066864e+17
loss=1.3018359798491808e+17
loss=1.2602949001588488e+17
loss=1.2222914314356629e+17
loss=1.2168859001146538e+17
loss=1.2099925795834435e+17
loss=1.1862497802372528e+17
loss=1.1455642789176349e+17
loss=1.0903350134620864e+17
loss=1.1224079646360408e+17
loss=1.0926199624652942e+17
loss=1.0825842271278485e+17
loss=1.0856390826158053e+17
loss=1.0942923285075365e+17
loss=1.1145652751343373e+17
loss=1.0988489680216549e+17
loss=1.1035762806508314e+17
loss=1.1022920091902629e+17
loss=1.0954244103407114e+17
loss=1.0746424308858694e+17
loss=1.0875365570990738e+17
loss=1.079106594122082e+17
loss=1.074322460493918e+17
loss=1.071511048902719e+17
loss=1.0745268292041827e+17
loss=1.0779606170964194e+17
loss=1.0910241220553917e+17
loss=1.1020776193657206e+17
loss=1.1190125394475339e+17
loss=1.1218840264870851e+17
loss=1.1175315004984333e+17
loss=1.1097040500603069e+17
loss=1.1058191165970093e+17
loss=1.1002357860611787e+17
loss=1.1030326456917936e+17
loss=1.1184262518883194e+17
loss=1.1377042990540238e+17
loss=1.1598251794477739e+17
loss=1.1805122781208142e+17
loss=1.2034922538764184e+17
loss=1.2150818228508358e+17
loss=1.2142366907175598e+17
loss=1.2096278564787997e+17
loss=1.2062202683678803e+17
loss=1.2024166781157398e+17
loss=1.2249789104302822e+17
loss=1.2263232558661147e+17
loss=1.238814237217959e+17
loss=1.2553640796540152e+17
loss=1.2670924969660397e+17
loss=1.2989268645735397e+17
loss=1.3074952284682101e+17
loss=1.3105871211626803e+17
loss=1.3141359120299547e+17
loss=1.3231382043326109e+17
loss=1.3315631502932749e+17
loss=1.342418801297855e+17
loss=1.3466914684644614e+17
loss=1.3434542277519795e+17
loss=1.3425019852660131e+17
loss=1.3469667269125885e+17
loss=1.3569447244805578e+17
loss=1.3694848588153354e+17
loss=1.3741552268756101e+17
loss=1.3805209094187283e+17
loss=1.3873610507690563e+17
loss=1.400276328267948e+17
loss=1.4175499123683011e+17
loss=1.4367957960611467e+17
loss=1.4399461025100494e+17
loss=1.4143974856167656e+17
loss=1.3784440831726413e+17
loss=1.3602530165127893e+17
loss=1.3334765661715002e+17
loss=1.3177136137895253e+17
loss=1.33201747105848e+17
loss=1.3347416478742549e+17
loss=1.3411637570380214e+17
loss=1.3352061519522166e+17
loss=1.3380552645425942e+17
loss=1.3372703205473395e+17
loss=1.3313382592218547e+17
loss=1.3247338237454885e+17
loss=1.3199855947219662e+17
loss=1.3019151953573683e+17
loss=1.2857685971363107e+17
loss=1.2949824171599664e+17
loss=1.2856559633425246e+17
loss=1.2825226043788418e+17
loss=1.2868459762232208e+17
loss=1.2963614286313867e+17
loss=1.3191563207371894e+17
loss=1.3401426633850474e+17
loss=1.3556590193923208e+17
loss=1.3460802316843229e+17
loss=1.3372263622175864e+17
loss=1.3278097114581198e+17
loss=1.3189452220116611e+17
loss=1.3089907334587747e+17
loss=1.3138433633364267e+17
loss=1.3071392388129216e+17
loss=1.3004226141337834e+17
loss=1.3003717481763872e+17
loss=1.2954525079155142e+17
loss=1.2970152721198198e+17
loss=1.305502699712159e+17
loss=1.3101807094497914e+17
loss=1.312356335103815e+17
loss=1.312425104557496e+17
loss=1.3128254910199002e+17
loss=1.3155741861837728e+17
loss=1.3164326092464675e+17
loss=1.3201273577484742e+17
loss=1.3255247988597504e+17
loss=1.3227591991137283e+17
loss=1.3274753404279787e+17
loss=1.3426912000795136e+17
loss=1.3655194841187278e+17
loss=1.3967254617727296e+17
loss=1.3981665820085275e+17
loss=1.3884409061147989e+17
loss=1.3806313768149806e+17
loss=1.3752152491556594e+17
loss=1.3744250180475195e+17
loss=1.3880968100819264e+17
loss=1.4612623006183213e+17
loss=1.4617332975583165e+17
loss=1.461506470815907e+17
loss=1.4867273625030192e+17
loss=1.5139205557554896e+17
loss=1.556722171539347e+17
loss=1.5894676226631648e+17
loss=1.575845601946547e+17
loss=1.5555151103789203e+17
loss=1.5463411139748275e+17
loss=1.526615985362805e+17
loss=1.533515322483244e+17
loss=1.539614081393012e+17
loss=1.544878460728554e+17
loss=1.5532991297890787e+17
loss=1.5817995166281002e+17
loss=1.5771368938991357e+17
loss=1.572483293576199e+17
loss=1.5647639297185514e+17
loss=1.5585728678650906e+17
loss=1.556307293581607e+17
loss=1.5558976004466835e+17
loss=1.556461116975926e+17
loss=1.5602541391096973e+17
loss=1.5574609366470093e+17
loss=1.5586346902264758e+17
loss=1.5626969465629126e+17
loss=1.5653467701497578e+17
loss=1.5697811798217258e+17
loss=1.570527681494977e+17
loss=1.569201200654775e+17
loss=1.5688706169795782e+17
loss=1.570172141499527e+17
loss=1.5792860255565408e+17
loss=1.5757992118452064e+17
loss=1.572554572212761e+17
loss=1.567669890586619e+17
loss=1.5586063491056227e+17
loss=1.5264172744140106e+17
loss=1.460293629704847e+17
loss=1.39556500494304e+17
loss=1.4282160409893605e+17
loss=1.3794106763795568e+17
loss=1.3604964831992744e+17
loss=1.3569662640943992e+17
loss=1.354865971194831e+17
loss=1.3486162828010694e+17
loss=1.3267367189198734e+17
loss=1.3176990785880387e+17
loss=1.316878387880853e+17
loss=1.3118075628401418e+17
loss=1.3037655426713936e+17
loss=1.2861068964788926e+17
loss=1.2743732940871203e+17
loss=1.280263816610682e+17
loss=1.2686427397922378e+17
loss=1.2661057763432365e+17
loss=1.2713367247399955e+17
loss=1.2885545793992451e+17
loss=1.3261796179328318e+17
loss=1.49214254975109e+17
loss=1.3425529730033971e+17
loss=1.3864269880748206e+17
loss=1.4115790724728989e+17
loss=1.4275703151173808e+17
loss=1.4457015049345584e+17
loss=1.4595880745963763e+17
loss=1.4273775742687605e+17
loss=1.4264525856506992e+17
loss=1.4253440067546094e+17
loss=1.3869414395622618e+17
loss=1.3759305436667098e+17
loss=1.3273677883446261e+17
loss=1.3726237516903448e+17
loss=1.3808975988035232e+17
loss=1.3908777108894715e+17
loss=1.4130159095412957e+17
loss=1.420080332394114e+17
loss=1.4148661285508998e+17
loss=1.3945142622289354e+17
loss=1.3592265434796437e+17
loss=1.3206096942926614e+17
loss=1.334429519165519e+17
loss=1.3200861800372992e+17
loss=1.3081439474793803e+17
loss=1.3139816290770894e+17
loss=1.3328039003171011e+17
loss=1.3503257784087115e+17
loss=1.3546357777337474e+17
loss=1.3534689203259813e+17
loss=1.3512894025155915e+17
loss=1.3497627073829651e+17
loss=1.3434700486948027e+17
loss=1.3769855322059624e+17
loss=1.3506028468902128e+17
loss=1.3519974852896198e+17
loss=1.3594158078849798e+17
loss=1.3757216491396248e+17
loss=1.4037185122339394e+17
loss=1.4053795333692493e+17
loss=1.4082503924312165e+17
loss=1.4117474773300698e+17
loss=1.4149563667315298e+17
loss=1.4096932857434022e+17
loss=1.389313089033187e+17
loss=1.3681068003120125e+17
loss=1.3515876829056096e+17
loss=1.3337429073574774e+17
loss=1.3190437722096109e+17
loss=1.319893764188858e+17
loss=1.3182930088145922e+17
loss=1.3306251008490504e+17
loss=1.3411784191914272e+17
loss=1.3464851474714699e+17
loss=1.333421279539619e+17
loss=1.2908106008157834e+17
loss=1.2355113572291602e+17
loss=1.2602700317884403e+17
loss=1.243520353552087e+17
loss=1.2320938764671496e+17

/dcs/23/u2200504/thesis/envthesis/lib/python3.13/site-packages/scipy/linalg/_matfuncs.py:389: RuntimeWarning: overflow encountered in matmul
  eAw = eAw @ eAw
/dcs/23/u2200504/thesis/envthesis/lib/python3.13/site-packages/scipy/linalg/_matfuncs.py:389: RuntimeWarning: invalid value encountered in matmul
  eAw = eAw @ eAw

loss=1.2640148565884405e+17
loss=1.2629037163144083e+17
loss=1.26198915082286e+17
loss=1.2607779139990682e+17
loss=1.259902203206741e+17
loss=1.2588796168966107e+17
loss=1.2574917016459467e+17
loss=1.25859245393627e+17
loss=1.2606174524214477e+17
loss=1.2635545684926686e+17
loss=1.265270900160773e+17
loss=1.2652335653284238e+17
loss=1.2642651222407616e+17
loss=1.2641571161552006e+17
loss=1.2644948893418986e+17
loss=1.2641881005603579e+17
loss=1.2647986700711264e+17
loss=1.265642557297513e+17
loss=1.2683581539381069e+17
loss=1.2705990180900056e+17
loss=1.2721335375899643e+17
loss=1.2764724852608478e+17
loss=1.2740533726678558e+17
loss=1.275862454687333e+17
loss=1.2760932429132114e+17
loss=1.2763801740104642e+17
loss=1.2774416559335976e+17
loss=1.2775324177129797e+17
loss=1.2780839390549331e+17
loss=1.2786658040869107e+17
loss=1.2809767683198136e+17
loss=1.2836870945221941e+17
loss=1.2831326559162622e+17
loss=1.2822343804088606e+17
loss=1.2812308114186845e+17
loss=1.2796143512828986e+17
loss=1.2780944558951579e+17
loss=1.2788375307265899e+17
loss=1.27703123060551e+17
loss=1.2743905945775917e+17
loss=1.2738451381697389e+17
loss=1.2755933621450605e+17
loss=1.2759022066222224e+17
loss=1.276571829794366e+17
loss=1.2770611418461338e+17
loss=1.2780342106340949e+17
loss=1.2774525798103872e+17
loss=1.2770700297705725e+17
loss=1.2763302995694368e+17
loss=1.2757463452216176e+17
loss=1.2759337006254126e+17
loss=1.2771983824440416e+17
loss=1.2813625407244315e+17
loss=1.2852624141066237e+17
loss=1.295897079360781e+17
loss=1.2881039564947914e+17
loss=1.2910948112252291e+17
loss=1.2948138437628832e+17
loss=1.2964840779809091e+17
loss=1.2965332219513406e+17
loss=1.2943871911816032e+17
loss=1.2900509367736571e+17
loss=1.2853887893861795e+17
loss=1.2816524955927794e+17
loss=1.2814008982075002e+17
loss=1.2841989661795942e+17
loss=1.2883846321016842e+17
loss=1.2927537554833917e+17
loss=1.2855079555812654e+17
loss=1.289532361414862e+17
loss=1.2887098280493952e+17
loss=1.284480535340682e+17
loss=1.2803299845868634e+17
loss=1.2763893420136336e+17
loss=1.2727727856538026e+17
loss=1.2715842172599362e+17
loss=1.2842389213049307e+17
loss=1.2767613691439869e+17
loss=1.2822385292889643e+17
loss=1.2881234408257269e+17
loss=1.2965194593246678e+17
loss=1.3007824464214608e+17
loss=1.301013806793642e+17
loss=1.2976093919866733e+17
loss=1.2953409818863971e+17
loss=1.293489149339981e+17
loss=1.2924580317402182e+17
loss=1.2924945073344187e+17
loss=1.2922514873414403e+17
loss=1.2926611881930242e+17
loss=1.2926752761474762e+17
loss=1.2911642117747718e+17
loss=1.2826334766089304e+17
loss=1.2891249875939203e+17
loss=1.283960128979088e+17
loss=1.277608873519881e+17
loss=1.270772789445562e+17
loss=1.2684003112526408e+17
loss=1.2681202055301302e+17
loss=1.2661998211636616e+17
loss=1.264031256898031e+17
loss=1.262863353824551e+17
loss=1.2654325983117397e+17
loss=1.2641289983132051e+17
loss=1.2658774111045018e+17
loss=1.266445789187442e+17
loss=1.2693088788900294e+17
loss=1.2668726899189574e+17
loss=1.2633717846297547e+17
loss=1.2563691653698086e+17
loss=1.2499232323565776e+17
loss=1.2462718623896922e+17
loss=1.2429770088776154e+17
loss=1.2429324995033541e+17
loss=1.2437587237299218e+17
loss=1.2432658172040525e+17
loss=1.2434407168366758e+17
loss=1.243268626485277e+17
loss=1.2420697593093643e+17
loss=1.2409750181100531e+17
loss=1.235443959754964e+17
loss=1.2339953280216661e+17
loss=1.235254196900405e+17
loss=1.2371141348919085e+17
loss=1.2392984027382874e+17
loss=1.2444041531478736e+17
loss=1.2547810131550693e+17
loss=1.2580524990338043e+17
loss=1.2564366122323736e+17
loss=1.2525696803626427e+17
loss=1.246468569982085e+17
loss=1.2360554932790067e+17
loss=1.225099163647165e+17
loss=1.213083967195192e+17
loss=1.2124320715707262e+17
loss=1.2193350342771955e+17
loss=1.2295071595392594e+17
loss=1.2331256923086496e+17
loss=1.2378790879151312e+17
loss=1.2381512940178549e+17
loss=1.2375022581710797e+17
loss=1.2309143673207672e+17
loss=1.231383690088743e+17
loss=1.2301500907273502e+17
loss=1.2327151993812989e+17
loss=1.2410002477087082e+17
loss=1.2491880074000269e+17
loss=1.259287443884808e+17
loss=1.2721554135549197e+17
loss=1.2743787456403251e+17
loss=1.2708041181087488e+17
loss=1.2683931374230355e+17
loss=1.2686404503455048e+17
loss=1.2660095808047603e+17
loss=1.2706659598113032e+17
loss=1.2769539106026296e+17
loss=1.2787265066513123e+17
loss=1.2783210801079878e+17
loss=1.2731321399758584e+17
loss=1.2685807047887326e+17
loss=1.2605651054760718e+17
loss=1.2586101370658e+17
loss=1.2569680884930178e+17
loss=1.2509070500605667e+17
loss=1.2420011032586397e+17
loss=1.2377296714055752e+17
loss=1.2315343206406366e+17
loss=1.2346278774792566e+17
loss=1.2433153148201957e+17
loss=1.2481879983735808e+17
loss=1.2622360475392907e+17
loss=1.2733918163126992e+17
loss=1.2765065933664558e+17
loss=1.2767374494220173e+17
loss=1.2772781616025638e+17
loss=1.275863431486273e+17
loss=1.271545096865799e+17
loss=1.266378318977278e+17
loss=1.2676084143006146e+17
loss=1.2909340172517485e+17
loss=1.315577066175514e+17
loss=1.3286769109997302e+17
loss=1.3382264402717912e+17
loss=1.3393231331317094e+17
loss=1.3373362216533866e+17
loss=1.3327545821572616e+17
loss=1.331396005454523e+17
loss=1.3297192954328166e+17
loss=1.3285856357968232e+17
loss=1.3290309066390613e+17
loss=1.330310975348959e+17
loss=1.3337154600505605e+17
loss=1.3356689465517203e+17
loss=1.3371375351844749e+17
loss=1.341539578450074e+17
loss=1.3479624764528373e+17
loss=1.3578206462299603e+17
loss=1.359091280939331e+17
loss=1.357616260606301e+17
loss=1.3550360287432184e+17
loss=1.3511421051901363e+17
loss=1.3578612613920496e+17
loss=1.3507710826814725e+17
loss=1.3496088909284042e+17
loss=1.3520062622968334e+17
loss=1.3560429700334075e+17
loss=1.3672189883002544e+17
loss=1.3621338495741478e+17
loss=1.3600168671377315e+17
loss=1.3555861013964754e+17
loss=1.3472914092527742e+17
loss=1.3385689699245446e+17
loss=1.3376925113861091e+17
loss=1.334945148686422e+17
loss=1.3309444277923302e+17
loss=1.3232974096517555e+17
loss=1.319379985921898e+17
loss=1.3181947890362723e+17
loss=1.3226244481034478e+17
loss=1.3327229147846806e+17
loss=1.3509207436462282e+17
loss=1.3502873329290989e+17
loss=1.3453431070336173e+17
loss=1.3397123732154821e+17
loss=1.3278012909258157e+17
loss=1.330484321766574e+17
loss=1.329787835123215e+17
loss=1.3278792506809523e+17
loss=1.3250921702373475e+17
loss=1.3230533221170842e+17
loss=1.3213989414726053e+17
loss=1.3253408726191517e+17
loss=1.337884912019471e+17
loss=1.3559670949229987e+17
loss=1.3579929002818682e+17
loss=1.3618778510579792e+17
loss=1.3686429494225685e+17
loss=1.3821446949787282e+17
loss=1.3955775519540702e+17
loss=1.3961574514863062e+17
loss=1.3946833492774318e+17
loss=1.3946156674051806e+17
loss=1.3977323853634787e+17
loss=1.4100571876678531e+17
loss=1.4053630585107882e+17
loss=1.406690858701916e+17
loss=1.4123039707860947e+17
loss=1.4080748932771296e+17
loss=1.4056384945592918e+17
loss=1.401338206747345e+17
loss=1.3933516350488482e+17
loss=1.3931120272901109e+17
loss=1.4018963036179877e+17
loss=1.4186985402299611e+17
loss=1.4558550108603072e+17
loss=1.4856377595938208e+17
loss=1.4760816792782848e+17
loss=1.470762227472915e+17
loss=1.4631098087168e+17
loss=1.4495257990866595e+17
loss=1.4218825686859429e+17
loss=1.435742515878995e+17
loss=1.4217383454759434e+17
loss=1.4074697147459725e+17
loss=1.403509527269963e+17
loss=1.4036885032209579e+17
loss=1.4044768964793242e+17
loss=1.4024892747927752e+17
loss=1.395731796444839e+17
loss=1.3971312942073338e+17
loss=1.3859623021330397e+17
loss=1.3742278398227187e+17
loss=1.3649455379690251e+17
loss=1.353200206126341e+17
loss=1.3305387854449029e+17
loss=1.3092301734600891e+17
loss=1.298498175725184e+17
loss=1.2926637493431066e+17
loss=1.3259220953416802e+17
loss=1.290672837563361e+17
loss=1.2928916437158026e+17
loss=1.3016124533301574e+17
loss=1.3113093801383403e+17
loss=1.3022728939184816e+17
loss=1.2954420270406915e+17
loss=1.293240586873419e+17
loss=1.2882235165223704e+17
loss=1.2821315859082502e+17
loss=1.284263553026398e+17
loss=1.2826359440640635e+17
loss=1.282379972718416e+17
loss=1.2788839647296243e+17
loss=1.2798181864284467e+17
loss=1.2798134402110502e+17
loss=1.2765983171038128e+17
loss=1.2720127247750749e+17
loss=1.2696690971872475e+17
loss=1.2667408858590642e+17
loss=1.2598302403699336e+17
loss=1.2454235085227024e+17
loss=1.2414048383997925e+17
loss=1.237713046435735e+17
loss=1.2325640933546944e+17
loss=1.22839402689709e+17
loss=1.2235954289112144e+17
loss=1.2346594062644912e+17
loss=1.240482958376726e+17
loss=1.2661519144801446e+17
loss=1.278977062759982e+17
loss=1.3121003819536243e+17
loss=1.3271899837049544e+17
loss=1.34177960417769e+17
loss=1.357751248997295e+17
loss=1.4122689538338698e+17
loss=1.3619722389062848e+17
loss=1.3634979501536736e+17
loss=1.3626606610133816e+17
loss=1.3632508338861523e+17
loss=1.3669598103483542e+17
loss=1.4010939739549411e+17
loss=1.4105920789322134e+17
loss=1.4098951908906942e+17
loss=1.4155968808512288e+17
loss=1.4247831342925176e+17
loss=1.4515295233382976e+17
loss=1.4958713960835005e+17
loss=1.4945130447880714e+17
loss=1.492305414130327e+17
loss=1.488031900001699e+17
loss=1.4788912820033245e+17
loss=1.4496757540045568e+17
loss=1.4255759115531315e+17
loss=1.411845487917033e+17
loss=1.4132649101453048e+17
loss=1.4142806526176824e+17
loss=1.4171936847907928e+17
loss=1.4266228118137894e+17
loss=1.4464520916627414e+17
loss=1.455302970254657e+17
loss=1.4600702635067894e+17
loss=1.4617601420425738e+17
loss=1.4622972183261536e+17
loss=1.4637432129379405e+17
loss=1.465885945446757e+17
loss=1.4675258220439325e+17
loss=1.4710887565379392e+17
loss=1.473280849836719e+17
loss=1.4824237534987142e+17
loss=1.504631273503555e+17
loss=1.5393286729648858e+17
loss=1.5588278965020614e+17
loss=1.590380556869912e+17
loss=1.548077427199116e+17
loss=1.5084531632962355e+17
loss=1.4806337059653677e+17
loss=1.428681531617099e+17
loss=1.3860183939093376e+17
loss=1.338698846761584e+17
loss=1.3488160870579763e+17
loss=1.3660633846654e+17
loss=1.3805690301287562e+17
loss=1.3803887744927984e+17
loss=1.3681301228008786e+17
loss=1.3135786773083091e+17
loss=1.289669128538269e+17
loss=1.2471834142032003e+17
loss=1.2282840878762514e+17
loss=1.2330385494492558e+17
loss=1.2380697862930582e+17
loss=1.255308298239656e+17
loss=1.2717606328278662e+17
loss=1.2617574293843922e+17
loss=1.266918191056684e+17
loss=1.2700730008614821e+17
loss=1.2644785823159051e+17
loss=1.2609798933516933e+17
loss=1.2518123411610669e+17
loss=1.2489581630031565e+17
loss=1.2623956941276432e+17
loss=1.2828754928546888e+17
loss=1.2879946293197146e+17
loss=1.2982762555369576e+17
loss=1.3070039389402634e+17
loss=1.3220070047979165e+17
loss=1.3223803407664922e+17
loss=1.3146579350621176e+17
loss=1.2960733990351224e+17
loss=1.2852761494886787e+17
loss=1.2664427417457398e+17
loss=1.2454380105294808e+17
loss=1.2465127968694547e+17
loss=1.2763105183081269e+17
loss=1.3156878095604842e+17
loss=1.2854031798696957e+17
loss=1.299565876699535e+17
loss=1.3027308649125936e+17
loss=1.3253281380283187e+17
loss=1.335725116785744e+17
loss=1.3355846212018365e+17
loss=1.3448340012031342e+17
loss=1.3382698358148963e+17
loss=1.3245409743911258e+17
loss=1.3278928244937054e+17
loss=1.3338064655421757e+17
loss=1.342261816256294e+17
loss=1.3474948584094878e+17
loss=1.344133409403087e+17
loss=1.3183457902104867e+17
loss=1.2903375193388872e+17
loss=1.2903830448786234e+17
loss=1.2876913693283267e+17
loss=1.2833531828649861e+17
loss=1.2781672063238435e+17
loss=1.281213433013118e+17
loss=1.2884795128621915e+17
loss=1.2955726322475565e+17
loss=1.3026519371291014e+17
loss=1.2975349504189995e+17
loss=1.2816059600092379e+17
loss=1.2737710391946538e+17
loss=1.2772593672124205e+17
loss=1.2747838555720712e+17
loss=1.2659636056179888e+17
loss=1.2633380248934219e+17
loss=1.2565315910137307e+17
loss=1.259522997859926e+17
loss=1.2607781363144722e+17
loss=1.26171387280395e+17
loss=1.2676463336284667e+17
loss=1.2717075089264622e+17
loss=1.275363196642474e+17
loss=1.28311192042811e+17
loss=1.2846977112118864e+17
loss=1.2851433349865555e+17
loss=1.2904351710957014e+17
loss=1.301804667207647e+17
loss=1.3105339593394544e+17
loss=1.3186803826488469e+17
loss=1.3197941604402466e+17
loss=1.3178987238396856e+17
loss=1.3113857181160379e+17
loss=1.3121839524630614e+17
loss=1.3103323309667282e+17
loss=1.3096964254241629e+17
loss=1.3152437500779229e+17
loss=1.3336878940330902e+17
loss=1.3476037859596165e+17
loss=1.369824550095415e+17
loss=1.3928838895993544e+17
loss=1.4059611040582144e+17
loss=1.414446472888267e+17
loss=1.4156120727841294e+17
loss=1.4149239031598805e+17
loss=1.4212213202320626e+17
loss=1.4154479968655832e+17
loss=1.4166708175469485e+17
loss=1.4208430860942133e+17
loss=1.4263001238319174e+17
loss=1.4277977653720165e+17
loss=1.42519106733968e+17
loss=1.419604595154034e+17
loss=1.4075862006514563e+17
loss=1.3944390119270971e+17
loss=1.3855102657683106e+17
loss=1.3849500846696826e+17
loss=1.3881883079024008e+17
loss=1.39623409258904e+17
loss=1.4068172590485878e+17
loss=1.4160415865802051e+17
loss=1.4065024972822115e+17
loss=1.4121025251087566e+17
loss=1.4105629964354224e+17
loss=1.4071576392306181e+17
loss=1.4030576481862555e+17
loss=1.3956532978399472e+17
loss=1.3859836718900797e+17
loss=1.3913637389112362e+17
loss=1.3893356915358035e+17
loss=1.390809054297897e+17
loss=1.3919733510355514e+17
loss=1.3947246372533757e+17
loss=1.3974155649217434e+17
loss=1.3993213902324853e+17
loss=1.3970449232884611e+17
loss=1.3824912745857507e+17
loss=1.3696927182993597e+17
loss=1.3555157154927328e+17
loss=1.341042740213153e+17
loss=1.3241183847522314e+17
loss=1.3177058708161942e+17
loss=1.3253298794227147e+17
loss=1.3328165549970971e+17
loss=1.333532513921809e+17
loss=1.3303741519571128e+17
loss=1.3026131776631952e+17
loss=1.2859351615494589e+17
loss=1.2827558632009514e+17
loss=1.2801313761014685e+17
loss=1.278414130459472e+17
loss=1.2788042033796155e+17
loss=1.2778201157327907e+17
loss=1.2800780980295736e+17
loss=1.2813460610938829e+17
loss=1.2789342936572082e+17
loss=1.2692584017625838e+17
loss=1.258154975683375e+17
loss=1.251539574473059e+17
loss=1.24472977077304e+17
loss=1.2423221245870726e+17
loss=1.2448023831733928e+17
loss=1.2502401717367448e+17
loss=1.254016417093448e+17
loss=1.2547107723573075e+17
loss=1.2540229900078944e+17
loss=1.253219297540103e+17
loss=1.2523222005995072e+17
loss=1.2581098596366995e+17
loss=1.2548957910658003e+17
loss=1.2558957390099632e+17
loss=1.2617224101202942e+17
loss=1.2694701393163506e+17
loss=1.2830249756684299e+17
loss=1.2911994479853386e+17
loss=1.3009827410795011e+17
loss=1.3065101266995179e+17
loss=1.3054823425620488e+17
loss=1.3038490525555962e+17
loss=1.2994105519457974e+17
loss=1.2923388097246867e+17
loss=1.2862693692872139e+17
loss=1.2873732394986317e+17
loss=1.3517972831821574e+17
loss=1.2918506571440829e+17
loss=1.301296405700788e+17
loss=1.3075047583283602e+17
loss=1.3099323946286083e+17
loss=1.3105113186602064e+17
loss=1.3099854858822677e+17
loss=1.308009607136327e+17
loss=1.3074845377210365e+17
loss=1.3075872459987811e+17
loss=1.3037261803241014e+17
loss=1.297126182952477e+17
loss=1.2940994614450125e+17
loss=1.2788757555582789e+17
loss=1.272603626370057e+17
loss=1.2751503437653002e+17
loss=1.2741308338190413e+17
loss=1.2764023285366704e+17
loss=1.2792560141564939e+17
loss=1.283112964973207e+17
loss=1.2893555928445846e+17
loss=1.2852609821120022e+17
loss=1.2892808215157131e+17
loss=1.2919111639249339e+17
loss=1.2862977377080958e+17
loss=1.2886736107734026e+17
loss=1.2836092058616067e+17
loss=1.2794324793835971e+17
loss=1.2780099722116976e+17
loss=1.280488976207174e+17
loss=1.2889947546517147e+17
loss=1.2836968537061875e+17
loss=1.2870270308756264e+17
loss=1.290490337528775e+17
loss=1.2946442231251083e+17
loss=1.3002770878615094e+17
loss=1.3079074150663786e+17
loss=1.3230099400324072e+17
loss=1.3124848278248707e+17
loss=1.3159644204014514e+17
loss=1.3109895822406018e+17
loss=1.307638694044186e+17
loss=1.30054465856026e+17
loss=1.2879816158608018e+17
loss=1.281937556962641e+17
loss=1.27546101250619e+17
loss=1.2873501261990626e+17
loss=1.3061098015150486e+17
loss=1.3136498627330557e+17
loss=1.3278105141780512e+17
loss=1.3199266643596123e+17
loss=1.3023403275529869e+17
loss=1.2840971376824299e+17
loss=1.2593623887244264e+17
loss=1.251363795574222e+17
loss=1.2551288940608605e+17
loss=1.2562246145325339e+17
loss=1.2587503781849965e+17
loss=1.2600200246722288e+17
loss=1.2620350309880226e+17
loss=1.2629817083024336e+17
loss=1.261126218356495e+17
loss=1.258334905051939e+17
loss=1.2565616354452662e+17
loss=1.2519244181547472e+17
loss=1.2457228994993488e+17
loss=1.2443747213250754e+17
loss=1.2494044746985302e+17
loss=1.2622238348729744e+17
loss=1.2544985277001264e+17
loss=1.260986473008314e+17
loss=1.2664160763516368e+17
loss=1.2725574894500117e+17
loss=1.2798062527147978e+17
loss=1.2756969518803098e+17
loss=1.2712358724516875e+17
loss=1.2596517920458358e+17
loss=1.2465178977304614e+17
loss=1.2415098583984962e+17
loss=1.234898092297047e+17
loss=1.2290904278472189e+17
loss=1.2315509724439493e+17
loss=1.2293200246898138e+17
loss=1.233354680867267e+17
loss=1.238795440223886e+17
loss=1.243625136203991e+17
loss=1.248339133134129e+17
loss=1.235121609642254e+17
loss=1.2350947173313133e+17
loss=1.2305808491899611e+17
loss=1.2249496888199378e+17
loss=1.2199692285781688e+17
loss=1.2142434936985528e+17
loss=1.2181865580179155e+17
loss=1.2252515879238589e+17
loss=1.2280385963243011e+17
loss=1.2325154886939766e+17
loss=1.234658445562766e+17
loss=1.235442939799758e+17
loss=1.2335918306999171e+17
loss=1.2370971576281968e+17
loss=1.2338744901566557e+17
loss=1.2336399731994536e+17
loss=1.2358214496185766e+17
loss=1.2395884122901667e+17
loss=1.246617012397412e+17
loss=1.2492802979370109e+17
loss=1.2509247859728746e+17
loss=1.2510875421354091e+17
loss=1.2478606053981291e+17
loss=1.2446562346495216e+17
loss=1.2442036579748445e+17
loss=1.2412976664931555e+17
loss=1.237384836567361e+17
loss=1.2370821576661374e+17
loss=1.2916369363328762e+17
loss=1.2497448974845069e+17
loss=1.2591054198607685e+17
loss=1.2808891244640803e+17
loss=1.2965548666969923e+17
loss=1.3082841718845698e+17
loss=1.3095040201923864e+17
loss=1.3087551744838102e+17
loss=1.3100015084697104e+17
loss=1.3087694757470371e+17
loss=1.3085069772332106e+17
loss=1.3090022277424506e+17
loss=1.312160595792677e+17
loss=1.3160869382768915e+17
loss=1.3230151825495917e+17
loss=1.3287742123216331e+17
loss=1.3334215602374211e+17
loss=1.3319667594393565e+17
loss=1.3314573411807229e+17
loss=1.3321749857979266e+17
loss=1.3352083023938963e+17
loss=1.344779419241454e+17
loss=1.3395979903425754e+17
loss=1.3482648388131795e+17
loss=1.3642949375067822e+17
loss=1.3812363618601606e+17
loss=1.3967653928534206e+17
loss=1.4007858047957267e+17
loss=1.394159018185939e+17
loss=1.3843166348060778e+17
loss=1.3738845758436909e+17
loss=1.3629788863996069e+17
loss=1.353307235394951e+17
loss=1.3411774994835354e+17
loss=1.3480721000778538e+17
loss=1.3459624263025869e+17
loss=1.3497664498485229e+17
loss=1.3594054408660293e+17
loss=1.3565593737349256e+17
loss=1.3466563470273702e+17
loss=1.336634633148191e+17
loss=1.3284979565896942e+17
loss=1.3270638433730266e+17
loss=1.325887077690888e+17
loss=1.3242254342247878e+17
loss=1.3206188884605429e+17
loss=1.3148924619083213e+17
loss=1.3097963566303254e+17
loss=1.306831252653468e+17
loss=1.3076675856060734e+17
loss=1.3087878046099402e+17
loss=1.3042540582072344e+17
loss=1.299313368963551e+17
loss=1.29740122180037e+17
loss=1.2972737683269728e+17
loss=1.2982630212495422e+17
loss=1.3016212915372147e+17
loss=1.3046589342201197e+17
loss=1.3088434868059826e+17
loss=1.314780201399753e+17
loss=1.3191350072606082e+17
loss=1.3143447057697941e+17
loss=1.3040764640018048e+17
loss=1.300397457516506e+17
loss=1.2976306565715194e+17
loss=1.2811541597307227e+17
loss=1.2751281006172512e+17
loss=1.2746737472539224e+17
loss=1.2682531895759302e+17
loss=1.2587127944556122e+17
loss=1.2537528535550293e+17
loss=1.2486281715440779e+17
loss=1.2465733894221134e+17

/dcs/23/u2200504/thesis/recidivism-causal/code/dagslam/DAGSLAM Causal Bayesian Network Structure Learning of Mixed Type Data/_dagslam/DAGSLAM.py:104: RuntimeWarning: invalid value encountered in logaddexp
  * (np.logaddexp(0, M[..., j]) - X[..., j] * M[..., j])
/dcs/23/u2200504/thesis/envthesis/lib/python3.13/site-packages/numpy/linalg/linalg.py:2120: RuntimeWarning: invalid value encountered in slogdet
  sign, logdet = _umath_linalg.slogdet(a, signature=signature)

loss=2.3326164172764487e+83
loss=2.346058821783571e+83
loss=2.3548267678038477e+83
loss=2.3593888022182244e+83
loss=2.354999988373488e+83
loss=2.339954296149285e+83
loss=2.3321743218049392e+83
loss=2.3278059419828532e+83
loss=2.3330777689491166e+83
loss=2.349189802025418e+83
loss=2.3974916675158462e+83
loss=2.4045561366572728e+83
loss=2.4084582461297624e+83
loss=2.4090309989535301e+83
loss=2.4092622227623055e+83
loss=2.4092127111779858e+83
loss=2.4102196505976594e+83
loss=2.4075898731471704e+83
loss=2.4062561160420302e+83
loss=2.4044735275986565e+83
loss=2.4007566013288406e+83
loss=2.3995489010613284e+83
loss=2.3994972312715192e+83
loss=2.3989621091538253e+83
loss=2.4000943878570224e+83
loss=2.4021070844064613e+83
loss=2.4048025025577638e+83
loss=2.4046990347216513e+83
loss=2.401115402580709e+83
loss=2.3940686946736455e+83
loss=2.3814514420852614e+83
loss=2.3729205518760718e+83
loss=2.364109441201475e+83
loss=2.3672006025216295e+83
loss=2.3765069884877222e+83
loss=2.3831678063652357e+83
loss=2.3935098014564397e+83
loss=2.3990012544325743e+83
loss=2.406525138394313e+83
loss=2.4157114475897281e+83
loss=2.4115392004264237e+83
loss=2.42014694065595e+83
loss=2.4277518082590202e+83
loss=2.444153838002502e+83
loss=2.461096129626919e+83
loss=2.50414705373153e+83
loss=2.4823081654951403e+83
loss=2.490218111418099e+83
loss=2.4942271474431064e+83
loss=2.498156502306667e+83
loss=2.502958807450596e+83
loss=2.509993490774058e+83
loss=2.519536633706438e+83
loss=2.5215362347495957e+83
loss=2.5028274365133545e+83
loss=2.477372894531639e+83
loss=2.4564660303101974e+83
loss=2.448486601148027e+83
loss=2.4421484150345585e+83
loss=2.4547680452947496e+83
loss=2.4931100749769906e+83
loss=2.509564602786956e+83
loss=2.53806156703603e+83
loss=2.559882677172997e+83
loss=2.6181485139695643e+83
loss=2.611884488392176e+83
loss=2.6007123036895603e+83
loss=2.6081873357445097e+83
loss=2.70238494481649e+83
loss=2.635655319379547e+83
loss=2.663163570695815e+83
loss=2.7018615892143316e+83
loss=2.723598776816401e+83
loss=2.7270600484643105e+83
loss=2.7264068696384917e+83
loss=2.719432817301108e+83
loss=2.701690913834511e+83
loss=2.7155899735019676e+83
loss=2.6966650193783257e+83
loss=2.679889877910873e+83
loss=2.670877032738951e+83
loss=2.6600902077076884e+83
loss=2.660760142287321e+83
loss=2.6962092387226987e+83
loss=2.740132511998665e+83
loss=2.7520046094840324e+83
loss=2.766962778924469e+83
loss=2.7755251824846183e+83
loss=2.7914985159325836e+83
loss=2.811325386101593e+83
loss=2.794778968979231e+83
loss=2.7722782034884426e+83
loss=2.7588790154003744e+83
loss=2.737939809455179e+83
loss=2.745814838862437e+83
loss=2.7787175048625416e+83
loss=2.817508447399609e+83
loss=2.838247100091888e+83
loss=2.8248083055560383e+83
loss=2.7256032977439024e+83
loss=2.64293823550095e+83
loss=2.6715896381952964e+83
loss=2.56048691737566e+83
loss=2.5117835009074155e+83
loss=2.5048074454392307e+83
loss=2.5006822289352727e+83
loss=2.498184994863147e+83
loss=2.497761398719826e+83
loss=2.5004054039667765e+83
loss=2.518106944162321e+83
loss=2.5533656349819046e+83
loss=2.5271928704808633e+83
loss=2.5324373833348595e+83
loss=2.542447794315353e+83
loss=2.5401430213959586e+83
loss=2.537110988285909e+83
loss=2.53158814781024e+83
loss=2.530933096868728e+83
loss=2.532573928531152e+83
loss=2.5391800316255033e+83
loss=2.5543866309614164e+83
loss=2.541500696304252e+83
loss=2.5341212700382945e+83
loss=2.5090525102083344e+83
loss=2.4793165154351625e+83
loss=2.4743404833247754e+83
loss=2.468716380282872e+83
loss=2.4593803173269907e+83
loss=2.4572187461986493e+83
loss=2.4765240096701825e+83
loss=2.484780831799479e+83
loss=2.5116585354470843e+83
loss=2.561825703857342e+83
loss=2.6118898916539203e+83
loss=2.660636604408598e+83
loss=2.6658403216386e+83
loss=2.661028903094362e+83
loss=2.6534492151338335e+83
loss=2.6471674855382154e+83
loss=2.602239158151499e+83
loss=2.5831016289573236e+83
loss=2.5858843699738247e+83
loss=2.569656608973871e+83
loss=2.571848294769816e+83
loss=2.5740843076944897e+83
loss=2.5750783790565785e+83
loss=2.5699793183260443e+83
loss=2.590035274849159e+83
loss=2.549033557229194e+83
loss=2.529072474396014e+83
loss=2.5106856376429196e+83
loss=2.4739135131330867e+83
loss=2.4199557657047416e+83
loss=2.4489978353747684e+83
loss=2.4090603451870213e+83
loss=2.3874532845323719e+83
loss=2.3829059803007653e+83
loss=2.397180576461147e+83
loss=2.4537760028961857e+83
loss=2.492136983214186e+83
loss=2.490537826089862e+83
loss=2.4854540211246214e+83
loss=2.480210360029081e+83
loss=2.4721160931171535e+83
loss=2.460006285313126e+83
loss=2.466238728866863e+83
loss=2.4589436262094803e+83
loss=2.466080706488986e+83
loss=2.484315039736236e+83
loss=2.49428624001611e+83
loss=2.520507663163426e+83
loss=2.524143527209303e+83
loss=2.523366564885421e+83
loss=2.5241994191591695e+83
loss=2.523387339608331e+83
loss=2.523472687722213e+83
loss=2.5229287341937306e+83
loss=2.5177530496087883e+83
loss=2.507240874336772e+83
loss=2.491037156115699e+83
loss=2.4704857018367424e+83
loss=2.4695869787603353e+83
loss=2.4793403320344366e+83
loss=2.4871132576178316e+83
loss=2.4943149935111184e+83
loss=2.500503203894333e+83
loss=2.495553827378855e+83
loss=2.483662510336222e+83
loss=2.479574651273594e+83
loss=2.4760555524200833e+83
loss=2.472529060037583e+83
loss=2.468899009385611e+83
loss=2.4708877831176266e+83
loss=2.476503697072289e+83
loss=2.502080016869521e+83
loss=2.5132338300326654e+83
loss=2.5050712248308804e+83
loss=2.5059539794298356e+83
loss=2.5033657086407206e+83
loss=2.4948701929995303e+83
loss=2.4832326132253714e+83
loss=2.458629666729547e+83
loss=2.4714312527272455e+83
loss=2.457189363810642e+83
loss=2.444214872980576e+83
loss=2.4329177307346043e+83
loss=2.4228117036150373e+83
loss=2.401679744104138e+83
loss=2.409633254139335e+83
loss=2.408144073096319e+83
loss=2.4085644259000712e+83
loss=2.4039697931986066e+83
loss=2.3993615428776666e+83
loss=2.3831230386962057e+83
loss=2.3766871844617947e+83
loss=2.3799668082643128e+83
loss=2.3827915783668101e+83
loss=2.390872909984426e+83
loss=2.4037634567178156e+83
loss=2.410587664189177e+83
loss=2.3986309318903674e+83
loss=2.4041931447649207e+83
loss=2.394144049890142e+83
loss=2.3763414434940126e+83
loss=2.353554361886054e+83
loss=2.3152485177591703e+83
loss=2.3349712145674176e+83
loss=2.3188692731575822e+83
loss=2.2978286255496458e+83
loss=2.2882094198579386e+83
loss=2.310987100325066e+83
loss=2.289742276822513e+83
loss=2.296169003390745e+83
loss=2.30178770255838e+83
loss=2.3080430062497222e+83
loss=2.3122298658590512e+83
loss=2.3104939436821434e+83
loss=2.3064553781894304e+83
loss=2.2990334582317274e+83
loss=2.2926158153246268e+83
loss=2.2876546696794044e+83
loss=2.2820235978148085e+83
loss=2.288030320075384e+83
loss=2.304936927175465e+83
loss=2.3153178476812234e+83
loss=2.3357942138315246e+83
loss=2.3218724492737542e+83
loss=2.310748042604664e+83
loss=2.294341173641429e+83
loss=2.2867592560455268e+83
loss=2.2869173505361151e+83
loss=2.2850946416166066e+83
loss=2.2818145279125011e+83
loss=2.278272094769137e+83
loss=2.2729273663382436e+83
loss=2.2689141569753024e+83
loss=2.2616691240592325e+83
loss=2.2612950477115515e+83
loss=2.260937903528866e+83
loss=2.2585567110242508e+83
loss=2.2582200676217533e+83
loss=2.2589839511975443e+83
loss=2.255561589015267e+83
loss=2.2515674543142468e+83
loss=2.241910514923572e+83
loss=2.2285991522132369e+83
loss=2.215620919913572e+83
loss=2.2217632931774543e+83
loss=2.2159408897486371e+83
loss=2.2140337351455097e+83
loss=2.218464717715265e+83
loss=2.2268789305277826e+83
loss=2.231852774484597e+83
loss=2.2382291014851742e+83
loss=2.2440308377199213e+83
loss=2.2534619592973578e+83
loss=2.2415178610951798e+83
loss=2.2471296420883231e+83
loss=2.2463672406936743e+83
loss=2.2345446821665057e+83
loss=2.2226255697409446e+83
loss=2.2135790638513034e+83
loss=2.212867693743627e+83
loss=2.227009248389954e+83
loss=2.24884833322462e+83
loss=2.2637848204906546e+83
loss=2.2579758476391122e+83
loss=2.256265795539222e+83
loss=2.2534659317941024e+83
loss=2.250895050134977e+83
loss=2.263948050869848e+83
loss=2.2523882559223216e+83
loss=2.2522073737329095e+83
loss=2.2529144469515862e+83
loss=2.254440397351088e+83
loss=2.255611365199024e+83
loss=2.2576593647491668e+83
loss=2.257335534620154e+83
loss=2.2556107769503215e+83
loss=2.2569213491197352e+83
loss=2.256825602327766e+83
loss=2.2587197585401587e+83
loss=2.2623147385342145e+83
loss=2.2677286732088322e+83
loss=2.2712753675870832e+83
loss=2.272510121222025e+83
loss=2.2725602885613574e+83
loss=2.2720612912649537e+83
loss=2.2723125611568286e+83
loss=2.2727589628068712e+83
loss=2.2743503451519908e+83
loss=2.277452478519628e+83
loss=2.2874708693617988e+83
loss=2.295558822828448e+83
loss=2.2968241098457545e+83
loss=2.2990985112615718e+83
loss=2.3057009506641392e+83
loss=2.307857015120261e+83
loss=2.3112610622359293e+83
loss=2.313316234965118e+83
loss=2.3142632711999261e+83
loss=2.314798060964463e+83
loss=2.331627564135808e+83
loss=2.3371127136128437e+83
loss=2.3451378463085386e+83
loss=2.354319985171058e+83
loss=2.3720662045775687e+83
loss=2.388761838085256e+83
loss=2.382554057477982e+83
loss=2.3776166415537968e+83
loss=2.3688737402789296e+83
loss=2.358156809209563e+83
loss=2.3603444221322737e+83
loss=2.3616555190038153e+83
loss=2.3624022132785157e+83
loss=2.363574828900546e+83
loss=2.362150210131336e+83
loss=2.362742485217032e+83
loss=2.3632289511261578e+83
loss=2.3621749013794239e+83
loss=2.359231083417969e+83
loss=2.3602753561267678e+83
loss=2.35930171323465e+83
loss=2.358307081731758e+83
loss=2.3590796822916004e+83
loss=2.3638231198490716e+83
loss=2.3719935643628217e+83
loss=2.3675887067132424e+83
loss=2.3706829398184102e+83
loss=2.3737708505227678e+83
loss=2.3757763963110337e+83
loss=2.3810552796391054e+83
loss=2.3864244230453756e+83
loss=2.3888863384303246e+83
loss=2.3889553970844527e+83
loss=2.3879441105198416e+83
loss=2.3871020838536998e+83
loss=2.3909944070803418e+83
loss=2.3925008474587264e+83
loss=2.3913402824971984e+83
loss=2.3948482957748496e+83
loss=2.4015162408318517e+83
loss=2.4087074894538415e+83
loss=2.4168644889081295e+83
loss=2.4063167618395986e+83
loss=2.4052003880028695e+83
loss=2.3904858775976237e+83
loss=2.3741302780366654e+83
loss=2.3685320817971216e+83
loss=2.3645514407194992e+83
loss=2.3569005231406516e+83
loss=2.353259932631943e+83
loss=2.356201321645124e+83
loss=2.360834870979548e+83
loss=2.3632299048295146e+83
loss=2.3663958600050037e+83
loss=2.3619840695670823e+83
loss=2.3643996898121842e+83
loss=2.3605998991203113e+83
loss=2.357965843274746e+83
loss=2.3572465692850807e+83
loss=2.3582910232076735e+83
loss=2.362892517854838e+83
loss=2.364409849512591e+83
loss=2.3682949993713362e+83
loss=2.3656083791580218e+83
loss=2.363101732887592e+83
loss=2.3581278668259944e+83
loss=2.3489982622984404e+83
loss=2.3502717932234556e+83
loss=2.352502161469091e+83
loss=2.3545582301228888e+83
loss=2.356227544198581e+83
loss=2.3553389578399463e+83
loss=2.3536376658026746e+83
loss=2.35070091827545e+83
loss=2.348381185670341e+83
loss=2.3440071904918068e+83
loss=2.3412250479275685e+83
loss=2.34203851586302e+83
loss=2.345511229497339e+83
loss=2.3462903224971753e+83
loss=2.345722901320125e+83
loss=2.3391714321661986e+83
loss=2.3330198762457666e+83
loss=2.325440987159989e+83
loss=2.3230642529678748e+83
loss=2.3243446007776291e+83
loss=2.3257782168473247e+83
loss=2.3276600102710535e+83
loss=2.3295214885789923e+83
loss=2.332434376884991e+83
loss=2.343132822455074e+83
loss=2.3441691176145702e+83
loss=2.3450866872402617e+83
loss=2.346746864082229e+83
loss=2.348119069299698e+83
loss=2.3520677936239533e+83
loss=2.349856017055873e+83
loss=2.351559016003906e+83
loss=2.351545565233799e+83
loss=2.3505625685463972e+83
loss=2.3491746574276733e+83
loss=2.3489325378279065e+83
loss=2.3476119264923432e+83
loss=2.3460392498708928e+83
loss=2.3449628623805006e+83
loss=2.3456707259240163e+83
loss=2.3447119118324984e+83
loss=2.3452019330411908e+83
loss=2.3462464281514965e+83
loss=2.3469814102127305e+83
loss=2.3465399283466044e+83
loss=2.3469108736092585e+83
loss=2.3471051893228428e+83
loss=2.3467985747328868e+83
loss=2.3462657002804028e+83
loss=2.345547191809887e+83
loss=2.3445837063807206e+83
loss=2.343377453316569e+83
loss=2.3419197645049983e+83
loss=2.3389221618407192e+83
loss=2.3379785063112843e+83
loss=2.338345425317936e+83
loss=2.3403727079361067e+83
loss=2.3426567994563693e+83
loss=2.3440266580224768e+83
loss=2.34352083629548e+83
loss=2.3426562008758251e+83
loss=2.3420961268822077e+83
loss=2.3426144117483243e+83
loss=2.3432639188137293e+83
loss=2.3441156434551064e+83
loss=2.3469578715828693e+83
loss=2.34887510376363e+83
loss=2.3500245401738032e+83
loss=2.3493047351208888e+83
loss=2.3492307319475286e+83
loss=2.3488167827319002e+83
loss=2.3481633513796763e+83
loss=2.3471364001756031e+83
loss=2.346089302844952e+83
loss=2.3446180834336424e+83
loss=2.345509127090574e+83
loss=2.3470408498438683e+83
loss=2.3480511820169605e+83
loss=2.349360963622387e+83
loss=2.349100037665748e+83
loss=2.3482290312734465e+83
loss=2.3467311900673514e+83
loss=2.3459836589290392e+83
loss=2.3441640323655976e+83
loss=2.3427686001680488e+83
loss=2.3423058139452305e+83
loss=2.3415230245541561e+83
loss=2.3415000722075026e+83
loss=2.3415564043982614e+83
loss=2.3409896388176248e+83
loss=2.3402172950153834e+83
loss=2.3397261362199462e+83
loss=2.339647024782552e+83
loss=2.3394818438252913e+83
loss=2.3395182021201302e+83
loss=2.3423442189943893e+83
loss=2.3402525043553544e+83
loss=2.341379140916389e+83
loss=2.3436759919409475e+83
loss=2.3446350594879774e+83
loss=2.3446031074746222e+83
loss=2.3445945969466646e+83
loss=2.3445980968134395e+83
loss=2.344595753581487e+83
loss=2.3448915215871688e+83
h:nan
######################################################
iter:2
rho:1.0
loss=2.3448915215871688e+83
loss=2.3448915215871688e+83
loss=2.3448915215871688e+83
loss=2.3448915215871688e+83
loss=2.3448915215871688e+83
loss=2.3448915215871688e+83
loss=2.3448915215871688e+83
loss=2.3448915215871688e+83
loss=2.3448915215871688e+83
loss=2.3448915215871688e+83
loss=2.3448915215871688e+83
loss=2.3448915215871688e+83
loss=2.3448915215871688e+83
loss=2.3448915215871688e+83
loss=2.3448915215871688e+83
loss=2.3448915215871688e+83
loss=2.3448915215871688e+83
loss=2.3448915215871688e+83
loss=2.3448915215871688e+83
loss=2.3448915215871688e+83
loss=2.3448915215871688e+83
loss=2.3448915215871688e+83
loss=nan
  ERROR on treatment_mediator/job_training_policy.csv: array must not contain infs or NaNs
Processing: treatment_mediator/tax_incentive_policy.csv
iter:0
rho:1.0
loss=1725.5315418766895
loss=1725.5315418766895
loss=1725.5315418766895
loss=1725.5315418766895
loss=1725.5315418766895
loss=1725.5315418766895
loss=1725.5315418766895
loss=1725.5315418766895
loss=1725.5315418766895
loss=1725.5315418766895
loss=1725.5315418766895
loss=1725.5315418766895
loss=1725.5315418766895
loss=1725.5315418766895
loss=1725.5315418766895
loss=1725.5315418766895
loss=1725.5315418766895
loss=1725.5315418766895
loss=1725.5315418766895
loss=1725.5315418766895
loss=1725.5315418766895
loss=1725.5315418766895
loss=2317.7115072838496
loss=1722.5892495214707
loss=1720.0597565622138
loss=1669.6211803645965
loss=1602.4547239384538
loss=1582.3425939376482
loss=1561.3917707357818
loss=1544.3840930555077
loss=1541.927424012788
loss=1539.7008758578663
loss=1533.428906508119
loss=1521.9189310979832
loss=1490.8618338648223
loss=1458.9353711288427
loss=1350.532574267175
loss=1297.8230544775754
loss=1257.4021011073824
loss=1691.279645793183
loss=1292.8655913873313
loss=1261.7984271108653
loss=1258.1098325659816
loss=1257.5353202713725
loss=1257.4535844744876
loss=1257.4997542728804
loss=1257.4710145789202
loss=1257.4853878286608
loss=1257.4900952133144
loss=1236.593910071681
loss=1218.1753229809046
loss=1187.958727759364
loss=1166.7108337843192
loss=1144.9625385634627
loss=1157.3400985711487
loss=1192.2126216316212
loss=1143.3516044967912
loss=1118.734929370823
loss=1114.3333752161134
loss=1105.4823731201968
loss=1104.9532245000157
loss=1095.2080756809703
loss=1085.0139878096452
loss=1156.6659021625596
loss=1045.015619983244
loss=1017.8116352765607
loss=1060.2699414483354
loss=1010.8036819640356
loss=953.1043708336955
loss=864.2627927223892
loss=844.917980412226
loss=849.261027234256
loss=860.5997074381341
loss=851.221914386348
loss=850.1683583774476
loss=842.6818130638475
loss=844.7548653766969
loss=848.2621412443351
loss=849.6493544587049
loss=850.0449431725827
loss=850.1363038734937
loss=850.0676981524354
loss=850.0842186037089
loss=850.0712835493208
loss=1726.596841793382
loss=955.5595656294686
loss=864.7254079274771
loss=852.6809521842821
loss=850.6835528993207
loss=850.2424867409217
loss=850.1215754418301
loss=850.0853250360043
loss=850.0746803784197
loss=850.0719613645299
loss=850.0715001155608
loss=850.0713113797123
loss=850.0714315541298
loss=833.7636459756279
loss=842.0752278208678
loss=840.1379682777819
loss=835.6830771488243
loss=839.1759139843265
loss=836.1425337431236
loss=836.447285851908
loss=836.25195423887
loss=837.7557976681243
loss=836.4009744174838
loss=836.2766845571982
loss=835.973745079688
loss=835.4005347627985
loss=834.9466513127187
loss=835.1991223761106
loss=834.1237683126889
loss=834.8400079325664
loss=834.5161790771516
loss=834.3918000352579
loss=834.3304175091621
loss=834.3369551780529
loss=834.3887036824492
loss=834.3065358829125
loss=834.3017362215603
loss=834.2762859966906
loss=834.2369538492741
loss=867.0359950993598
loss=834.2370528263299
loss=834.1719657795037
loss=834.13588774359
loss=834.1461394378289
loss=834.1288719989243
loss=834.1123512875886
loss=834.1056173500679
loss=834.0600328662912
loss=834.0828374008389
loss=834.0697648710452
loss=834.0317801269327
loss=833.8894117541664
loss=834.8448697012687
loss=833.8755664389632
loss=833.8856262973775
loss=833.8889387863017
loss=833.8843468636672
loss=833.8325436721399
loss=833.8284091360329
loss=833.7681153949986
loss=833.7941098645889
loss=833.6923361480267
loss=833.6719352865904
loss=833.5377633770605
loss=833.0655719495492
loss=833.3712067882087
loss=833.121287779846
loss=833.1614709431259
loss=832.4527782413553
loss=833.0911967094216
loss=833.1480161398866
loss=833.0611552456463
loss=832.7428532874828
loss=831.4136588240161
loss=831.0812421382085
loss=831.3994784890688
loss=831.408722365534
loss=831.1810965360673
loss=829.9452127214095
loss=830.588703191945
loss=831.1804188919164
loss=830.7694147654474
loss=831.0186493804158
loss=830.0203065818106
loss=830.516174482446
loss=830.0531098192843
loss=830.2261426934748
loss=830.1252448881474
loss=830.3120479902589
loss=830.1452181036811
loss=829.9451380168587
loss=829.8431454854419
loss=829.6676272494834
loss=829.5155299069128
loss=829.1422680590889
loss=828.7368408141751
loss=828.8063070064522
loss=828.5920704634534
loss=828.7025690550638
loss=828.6702392362323
loss=828.5725383791298
loss=828.5475322207235
loss=828.5399044234131
loss=828.5181210032641
loss=828.5214464779539
loss=828.5172687348189
loss=828.510781752858
loss=828.5017858119136
loss=828.5006555889552
loss=828.4991427574687
loss=828.4984804891724
loss=828.4988874677947
loss=828.5003586951326
loss=828.4988328766801
loss=828.4986294415803
loss=828.4980098564723
loss=828.4973702433922
loss=828.4953392705243
loss=828.4933025220419
loss=828.5012592908141
loss=828.4941912683219
loss=828.4936520859077
loss=828.4904939105559
loss=828.4902520379991
loss=828.4891617243203
loss=828.4930895049231
loss=828.4879953653887
loss=828.487934424527
loss=828.4857066476123
loss=828.4815663824911
loss=828.4800037718635
loss=828.4803630879804
loss=828.4809200484824
loss=828.4807767141936
loss=828.4806078539794
loss=828.4803815030496
loss=828.4805390003627
loss=828.4805353517314
loss=828.48030634726
loss=828.479578554695
loss=828.4781923769789
loss=828.4789368443237
loss=828.4788695653987
loss=828.477995257259
loss=828.4773214264934
loss=828.4779133423924
loss=828.4778771387299
loss=828.4778943264669
loss=828.4775674565749
loss=828.477773570875
h:2.9200737273689556e+129
######################################################
iter:1
rho:1.0

/dcs/23/u2200504/thesis/recidivism-causal/code/dagslam/DAGSLAM Causal Bayesian Network Structure Learning of Mixed Type Data/_dagslam/DAGSLAM.py:104: RuntimeWarning: invalid value encountered in logaddexp
  * (np.logaddexp(0, M[..., j]) - X[..., j] * M[..., j])
/dcs/23/u2200504/thesis/envthesis/lib/python3.13/site-packages/numpy/linalg/linalg.py:2120: RuntimeWarning: invalid value encountered in slogdet
  sign, logdet = _umath_linalg.slogdet(a, signature=signature)
/dcs/23/u2200504/thesis/recidivism-causal/code/dagslam/DAGSLAM Causal Bayesian Network Structure Learning of Mixed Type Data/_dagslam/DAGSLAM.py:104: RuntimeWarning: invalid value encountered in logaddexp
  * (np.logaddexp(0, M[..., j]) - X[..., j] * M[..., j])
/dcs/23/u2200504/thesis/envthesis/lib/python3.13/site-packages/numpy/linalg/linalg.py:2120: RuntimeWarning: invalid value encountered in slogdet
  sign, logdet = _umath_linalg.slogdet(a, signature=signature)

,TP,FP,FN,TN,SHD,TPR,FPR,FDR,scenario,dataset,algo
0,2,11,7,29,18,0.222222,0.275000,0.846154,casual_effect,device_failure_data,dagslam
1,9,26,0,14,26,1.000000,0.650000,0.742857,casual_effect,student_tutoring_data,dagslam
2,3,1,0,12,1,1.000000,0.076923,0.250000,causal_direction_iv,clinical_trial_sem,dagslam
3,2,7,1,6,8,0.666667,0.538462,0.777778,causal_direction_iv,ecommerce_sem,dagslam
4,2,7,1,6,8,0.666667,0.538462,0.777778,causal_direction_iv,environment_sem,dagslam
5,3,6,0,7,6,1.000000,0.461538,0.666667,causal_direction_iv,marketing_sem,dagslam
6,0,3,4,9,7,0.000000,0.250000,1.000000,counterfactual_reasoning,climate_impact_sem,dagslam
7,0,3,4,9,7,0.000000,0.250000,1.000000,counterfactual_reasoning,clinical_trial_sem,dagslam
8,0,3,4,9,7,0.000000,0.250000,1.000000,counterfactual_reasoning,education_performance_sem,dagslam
9,0,3,4,9,7,0.000000,0.250000,1.000000,counterfactual_reasoning,investment_outcome_sem,dagslam
10,0,3,4,9,7,0.000000,0.250000,1.000000,counterfactual_reasoning,manufacturing_quality_sem,dagslam
11,2,0,0,7,0,1.000000,0.000000,0.000000,dag_structure_markequi,dag_structure_markequi_sem,dagslam
12,2,0,0,7,0,1.000000,0.000000,0.000000,dag_structure_markequi,sleep_alertness_productivity,dagslam
13,2,0,0,7,0,1.000000,0.000000,0.000000,dag_structure_markequi,study_comprehension_testscore,dagslam
14,2,0,0,7,0,1.000000,0.000000,0.000000,dag_structure_markequi,web_traffic_revenue,dagslam
15,4,5,1,6,6,0.800000,0.454545,0.555556,domain_shift,arthritis_trial,dagslam
16,4,5,1,6,6,0.800000,0.454545,0.555556,domain_shift,cardio_trial,dagslam
17,3,4,2,7,6,0.600000,0.363636,0.571429,domain_shift,cholesterol_trial,dagslam
18,4,4,1,7,5,0.800000,0.363636,0.500000,domain_shift,diabetes_trial,dagslam
19,4,1,1,10,2,0.800000,0.090909,0.200000,domain_shift,domain_shift_sem,dagslam
20,6,7,2,34,9,0.750000,0.170732,0.538462,mediation_outcome_confounder,exercise_intervention_study,dagslam
21,6,7,2,34,9,0.750000,0.170732,0.538462,mediation_outcome_confounder,language_learning_study,dagslam
22,7,8,1,33,9,0.875000,0.195122,0.533333,mediation_outcome_confounder,nutrition_program_study,dagslam
23,3,1,0,5,1,1.000000,0.166667,0.250000,moderation_effect,arthritis_pain_reduction,dagslam
24,3,1,0,5,1,1.000000,0.166667,0.250000,moderation_effect,depression_symptom_reduction,dagslam
25,3,0,0,6,0,1.000000,0.000000,0.000000,moderation_effect,hypertension_bp_reduction,dagslam
26,3,0,0,6,0,1.000000,0.000000,0.000000,moderation_effect,infection_bacteria_reduction,dagslam
27,3,0,0,6,0,1.000000,0.000000,0.000000,moderation_effect,moderation_effect_sem,dagslam
28,0,0,3,13,3,0.000000,0.000000,NaN,necessity_sufficiency,bridge_integrity,dagslam
29,0,0,3,13,3,0.000000,0.000000,NaN,necessity_sufficiency,factory_monitoring,dagslam
30,0,0,3,13,3,0.000000,0.000000,NaN,necessity_sufficiency,network_health,dagslam
31,0,0,3,13,3,0.000000,0.000000,NaN,necessity_sufficiency,patient_recovery,dagslam
32,0,0,3,13,3,0.000000,0.000000,NaN,necessity_sufficiency,stress_sem,dagslam
33,7,7,9,41,16,0.437500,0.145833,0.500000,sequential_mediator,sequential_mediation_dataset,dagslam
34,5,6,4,21,10,0.555556,0.222222,0.545455,treatment_mediator,education_subsidy_policy,dagslam

In [14]:
#encountered overflows in matrix multiplication

In [27]:
scores_df

,TP,FP,FN,TN,SHD,TPR,FPR,FDR,scenario,dataset,algo
0,2,11,7,29,18,0.222222,0.275000,0.846154,casual_effect,device_failure_data,dagslam
1,9,26,0,14,26,1.000000,0.650000,0.742857,casual_effect,student_tutoring_data,dagslam
2,3,1,0,12,1,1.000000,0.076923,0.250000,causal_direction_iv,clinical_trial_sem,dagslam
3,2,7,1,6,8,0.666667,0.538462,0.777778,causal_direction_iv,ecommerce_sem,dagslam
4,2,7,1,6,8,0.666667,0.538462,0.777778,causal_direction_iv,environment_sem,dagslam
5,3,6,0,7,6,1.000000,0.461538,0.666667,causal_direction_iv,marketing_sem,dagslam
6,0,3,4,9,7,0.000000,0.250000,1.000000,counterfactual_reasoning,climate_impact_sem,dagslam
7,0,3,4,9,7,0.000000,0.250000,1.000000,counterfactual_reasoning,clinical_trial_sem,dagslam
8,0,3,4,9,7,0.000000,0.250000,1.000000,counterfactual_reasoning,education_performance_sem,dagslam
9,0,3,4,9,7,0.000000,0.250000,1.000000,counterfactual_reasoning,investment_outcome_sem,dagslam
10,0,3,4,9,7,0.000000,0.250000,1.000000,counterfactual_reasoning,manufacturing_quality_sem,dagslam
11,2,0,0,7,0,1.000000,0.000000,0.000000,dag_structure_markequi,dag_structure_markequi_sem,dagslam
12,2,0,0,7,0,1.000000,0.000000,0.000000,dag_structure_markequi,sleep_alertness_productivity,dagslam
13,2,0,0,7,0,1.000000,0.000000,0.000000,dag_structure_markequi,study_comprehension_testscore,dagslam
14,2,0,0,7,0,1.000000,0.000000,0.000000,dag_structure_markequi,web_traffic_revenue,dagslam
15,4,5,1,6,6,0.800000,0.454545,0.555556,domain_shift,arthritis_trial,dagslam
16,4,5,1,6,6,0.800000,0.454545,0.555556,domain_shift,cardio_trial,dagslam
17,3,4,2,7,6,0.600000,0.363636,0.571429,domain_shift,cholesterol_trial,dagslam
18,4,4,1,7,5,0.800000,0.363636,0.500000,domain_shift,diabetes_trial,dagslam
19,4,1,1,10,2,0.800000,0.090909,0.200000,domain_shift,domain_shift_sem,dagslam
20,6,7,2,34,9,0.750000,0.170732,0.538462,mediation_outcome_confounder,exercise_intervention_study,dagslam
21,6,7,2,34,9,0.750000,0.170732,0.538462,mediation_outcome_confounder,language_learning_study,dagslam
22,7,8,1,33,9,0.875000,0.195122,0.533333,mediation_outcome_confounder,nutrition_program_study,dagslam
23,3,1,0,5,1,1.000000,0.166667,0.250000,moderation_effect,arthritis_pain_reduction,dagslam
24,3,1,0,5,1,1.000000,0.166667,0.250000,moderation_effect,depression_symptom_reduction,dagslam
25,3,0,0,6,0,1.000000,0.000000,0.000000,moderation_effect,hypertension_bp_reduction,dagslam
26,3,0,0,6,0,1.000000,0.000000,0.000000,moderation_effect,infection_bacteria_reduction,dagslam
27,3,0,0,6,0,1.000000,0.000000,0.000000,moderation_effect,moderation_effect_sem,dagslam
28,0,0,3,13,3,0.000000,0.000000,NaN,necessity_sufficiency,bridge_integrity,dagslam
29,0,0,3,13,3,0.000000,0.000000,NaN,necessity_sufficiency,factory_monitoring,dagslam
30,0,0,3,13,3,0.000000,0.000000,NaN,necessity_sufficiency,network_health,dagslam
31,0,0,3,13,3,0.000000,0.000000,NaN,necessity_sufficiency,patient_recovery,dagslam
32,0,0,3,13,3,0.000000,0.000000,NaN,necessity_sufficiency,stress_sem,dagslam
33,7,7,9,41,16,0.437500,0.145833,0.500000,sequential_mediator,sequential_mediation_dataset,dagslam
34,5,6,4,21,10,0.555556,0.222222,0.545455,treatment_mediator,education_subsidy_policy,dagslam

In [28]:
scores_path = project_root / "results" / "scores"/"scores_dagslam.csv"
scores_path.parent.mkdir(parents=True, exist_ok=True)
scores_df.to_csv(scores_path, index=False)